import { Injectable, signal, computed } from '@angular/core';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa' | 'or' | 'as';

export interface LanguageOption {
  code: Language;
  label: string;
  nativeLabel: string;
}

@Injectable({ providedIn: 'root' })
export class TranslateService {
  private currentLang = signal<Language>(this.loadSavedLanguage());

  lang = this.currentLang.asReadonly();
  langLabel = computed(() => this.languages.find(l => l.code === this.currentLang())?.nativeLabel || 'English');

  languages: LanguageOption[] = [
    { code: 'en', label: 'English', nativeLabel: 'English' },
    { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
    { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
    { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
    { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
    { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
    { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
    { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
    { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം' },
    { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ' },
    { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ' },
    { code: 'as', label: 'Assamese', nativeLabel: 'অসমীয়া' },
  ];

  private translations: Record<Language, Record<string, string>> = {
    en: {
      // Header
      'header.brandHindi': 'शिकायत प्रबंध प्रणाली',
      'header.brandEnglish': 'Complaint Management System',
      'header.home': 'HOME',
      'header.aboutUs': 'About us',
      'header.publicAwareness': 'Public Awareness',
      'header.contact': 'Contact',
      'header.physicalFiling': 'Physical Filing',
      'header.lastSignedIn': 'Last Signed in at',

      // Hero
      'hero.title': 'Your complaint to the RBI',
      'hero.titleHighlight': 'With Confidence',
      'hero.subtitle': 'Your trusted platform for complaint resolution - effortlessly file and track grievances against Regulated Entities.',
      'hero.fileComplaint': 'File a Complaint',
      'hero.alreadyFiled': 'Already filed a complaint?',
      'hero.trackOrWithdraw': 'Track or Withdraw Complaint',
      'hero.fileAppeal': 'File an Appeal',
      'hero.shareFeedback': 'Share Your Feedback',
      'hero.emailSimulation': 'Email Simulation (Demo)',
      'hero.needHelp': 'Need help ?',

      // Complaint Types
      'ct.findInstitution': 'Find your financial institution',
      'ct.title': 'You can file complaints about',
      'ct.searchPlaceholder': 'Search Entity',
      'ct.searchHint': 'Enter name or keyword of the bank or financial institution you want to search',
      'ct.allBanks': 'All Commercial Banks',
      'ct.nbfc': 'Non-Banking Financial Companies',
      'ct.creditInfo': 'Credit Information Companies',
      'ct.paymentSystem': 'Payment System Participants',

      // What We Do
      'whatwedo.tag': 'what we Do',
      'whatwedo.title': 'RBI streamlines the complaint resolution process for Indian Citizens.',
      'whatwedo.desc': 'RBI simplifies and expedites the complaint resolution process for Indian citizens, ensuring fair and timely resolutions.',
      'whatwedo.howToFile': 'How to file a complaint',
      'whatwedo.whatWeCanHelp': "What we can & can't help with",

      // Stats
      'stats.tag': 'statistics',
      'stats.received': 'Complaints Received',
      'stats.handled': 'Complaints Handled',
      'stats.resolved': 'Complaints Resolved',
      'stats.receivedValue': '9,50,000',
      'stats.handledValue': '8,75,000',
      'stats.resolvedValue': '96%',

      // Press
      'press.title': 'Press Release',
      'press.viewAll': 'View All',
      'press.readMore': 'Read more',
      'press.month1': 'Mar 22',
      'press.title1': 'BE(A)WARE – A Booklet on Modus Operandi of Financial Frauds',
      'press.desc1': 'The Reserve Bank has today released a booklet, "BE(A)WARE" on the common modus operandi used by fraudsters and precautions to be taken while carrying out various financial transactions.',
      'press.month2': 'Feb 22',
      'press.title2': 'RBI Cautions about Fake Websites in its Name',
      'press.desc2': 'The Reserve Bank has cautioned the public about fake websites using its name, and advised people to verify the authenticity of websites before sharing personal or financial information.',

      // Education
      'edu.tag': 'Public Awareness',
      'edu.title': 'Education and Awareness',
      'edu.watch': 'Watch',
      'edu.read': 'Read',
      'edu.card1Title': 'Basic Savings Bank Deposit Account (BSBDA)',
      'edu.card1Subtitle': 'Basic Savings Bank Deposit Account BSBDA',
      'edu.card2Title': 'Customer Liability in Unauthorised Electronic Banking Transactions',
      'edu.card2Subtitle': 'Customer Liability in Unauthorised Electronic Banking Transactions',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'A booklet on modus operandi of financial fraudsters',
      'edu.card4Title': 'Customer Liability in Unauthorised Electronic Banking Transactions',
      'edu.card4Subtitle': 'Basic Savings Bank Deposit Account BSBDA',

      // FAQ
      'faq.tag': 'FAQs',
      'faq.title': 'Frequently Asked Questions',
      'faq.q1': 'Which type of complaints can I lodge through this website?',
      'faq.a1': 'This website is meant to facilitate lodging of any complaint related to deficiency in services by entities regulated by the Reserve Bank of India such as Commercial Banks, Urban Cooperative Banks, Non-Banking Financial Companies, and Payment System Participants.',
      'faq.q2': 'How can I track my complaint status?',
      'faq.a2': 'You can track your complaint status by clicking on "Track Complaint" and entering your complaint reference number. You will be able to see the current status and any comments from the reviewing authority.',
      'faq.q3': 'What is the time limit for resolving a complaint?',
      'faq.a3': 'The regulated entity is required to resolve the complaint within 30 days of receipt. If you are not satisfied with the resolution or if the complaint is not resolved within 30 days, you may file a complaint on this portal.',

      // Dashboard
      'dashboard.home': 'Home',
      'dashboard.fileNew': 'File a New Complaint',
      'dashboard.history': 'Complaint History',
      'dashboard.id': 'ID',
      'dashboard.against': 'Complaint Against',
      'dashboard.date': 'Complaint Date',
      'dashboard.status': 'Status',
      'dashboard.comments': 'Comments',
      'dashboard.action': 'Action',
      'dashboard.withdraw': 'Withdraw',
      'dashboard.appeal': 'Appeal',
      'dashboard.act': 'Act',

      // File Complaint
      'file.title': 'Raise a Complaint',
      'file.step1': 'Tell Us About You',
      'file.step2': 'Entity Details',
      'file.step3': 'Final Step: Share Your Complaint',
      'file.next': 'Next',
      'file.previous': 'Previous',
      'file.submit': 'Submit',

      // Track
      'track.title': 'Track Your Complaint',
      'track.placeholder': 'Enter Complaint Number',
      'track.search': 'Search',

      // Common
      'common.search': 'Search',
      'common.cancel': 'Cancel',
      'common.close': 'Close',
      'common.loading': 'Loading...',
    },

    hi: {
      // Header
      'header.brandHindi': 'शिकायत प्रबंध प्रणाली',
      'header.brandEnglish': 'शिकायत प्रबंध प्रणाली',
      'header.home': 'होम',
      'header.aboutUs': 'हमारे बारे में',
      'header.publicAwareness': 'जन जागरूकता',
      'header.contact': 'संपर्क',
      'header.physicalFiling': 'भौतिक शिकायत',
      'header.lastSignedIn': 'अंतिम लॉगिन',

      // Hero
      'hero.title': 'RBI को आपकी शिकायत',
      'hero.titleHighlight': 'विश्वास के साथ',
      'hero.subtitle': 'शिकायत समाधान के लिए आपका विश्वसनीय मंच - विनियमित संस्थाओं के खिलाफ आसानी से शिकायत दर्ज करें और ट्रैक करें।',
      'hero.fileComplaint': 'शिकायत दर्ज करें',
      'hero.alreadyFiled': 'पहले से शिकायत दर्ज की है?',
      'hero.trackOrWithdraw': 'शिकायत ट्रैक या वापस लें',
      'hero.fileAppeal': 'अपील दर्ज करें',
      'hero.shareFeedback': 'अपनी प्रतिक्रिया साझा करें',
      'hero.emailSimulation': 'ईमेल सिमुलेशन (डेमो)',
      'hero.needHelp': 'मदद चाहिए?',

      // Complaint Types
      'ct.findInstitution': 'अपनी वित्तीय संस्था खोजें',
      'ct.title': 'आप इनके बारे में शिकायत दर्ज कर सकते हैं',
      'ct.searchPlaceholder': 'संस्था खोजें',
      'ct.searchHint': 'जिस बैंक या वित्तीय संस्था को खोजना है उसका नाम या कीवर्ड दर्ज करें',
      'ct.allBanks': 'सभी वाणिज्यिक बैंक',
      'ct.nbfc': 'गैर-बैंकिंग वित्तीय कंपनियाँ',
      'ct.creditInfo': 'क्रेडिट सूचना कंपनियाँ',
      'ct.paymentSystem': 'भुगतान प्रणाली प्रतिभागी',

      // What We Do
      'whatwedo.tag': 'हम क्या करते हैं',
      'whatwedo.title': 'RBI भारतीय नागरिकों के लिए शिकायत समाधान प्रक्रिया को सरल बनाता है।',
      'whatwedo.desc': 'RBI भारतीय नागरिकों के लिए शिकायत समाधान प्रक्रिया को सरल और त्वरित बनाता है, निष्पक्ष और समय पर समाधान सुनिश्चित करता है।',
      'whatwedo.howToFile': 'शिकायत कैसे दर्ज करें',
      'whatwedo.whatWeCanHelp': 'हम क्या कर सकते और क्या नहीं',

      // Stats
      'stats.tag': 'आंकड़े',
      'stats.received': 'शिकायतें प्राप्त',
      'stats.handled': 'शिकायतें संभाली',
      'stats.resolved': 'शिकायतें हल',
      'stats.receivedValue': '९,५०,०००',
      'stats.handledValue': '८,७५,०००',
      'stats.resolvedValue': '९६%',

      // Press
      'press.title': 'प्रेस विज्ञप्ति',
      'press.viewAll': 'सभी देखें',
      'press.readMore': 'और पढ़ें',
      'press.month1': 'मार्च 22',
      'press.title1': 'BE(A)WARE – वित्तीय धोखाधड़ी की कार्यप्रणाली पर पुस्तिका',
      'press.desc1': 'रिज़र्व बैंक ने आज "BE(A)WARE" पुस्तिका जारी की है जो धोखाधड़ी करने वालों की सामान्य कार्यप्रणाली और वित्तीय लेनदेन करते समय बरती जाने वाली सावधानियों पर आधारित है।',
      'press.month2': 'फ़र 22',
      'press.title2': 'RBI ने अपने नाम पर फर्जी वेबसाइटों के बारे में चेतावनी दी',
      'press.desc2': 'रिज़र्व बैंक ने जनता को अपने नाम पर बनी फर्जी वेबसाइटों के प्रति सचेत किया है और व्यक्तिगत या वित्तीय जानकारी साझा करने से पहले वेबसाइट की प्रामाणिकता सत्यापित करने की सलाह दी है।',

      // Education
      'edu.tag': 'जन जागरूकता',
      'edu.title': 'शिक्षा और जागरूकता',
      'edu.watch': 'देखें',
      'edu.read': 'पढ़ें',
      'edu.card1Title': 'बेसिक बचत बैंक जमा खाता (BSBDA)',
      'edu.card1Subtitle': 'बेसिक बचत बैंक जमा खाता BSBDA',
      'edu.card2Title': 'अनधिकृत इलेक्ट्रॉनिक बैंकिंग लेनदेन में ग्राहक देयता',
      'edu.card2Subtitle': 'अनधिकृत इलेक्ट्रॉनिक बैंकिंग लेनदेन में ग्राहक देयता',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'वित्तीय धोखाधड़ी करने वालों की कार्यप्रणाली पर पुस्तिका',
      'edu.card4Title': 'अनधिकृत इलेक्ट्रॉनिक बैंकिंग लेनदेन में ग्राहक देयता',
      'edu.card4Subtitle': 'बेसिक बचत बैंक जमा खाता BSBDA',

      // FAQ
      'faq.tag': 'अक्सर पूछे जाने वाले प्रश्न',
      'faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
      'faq.q1': 'इस वेबसाइट के माध्यम से मैं किस प्रकार की शिकायतें दर्ज कर सकता हूँ?',
      'faq.a1': 'यह वेबसाइट भारतीय रिज़र्व बैंक द्वारा विनियमित संस्थाओं जैसे वाणिज्यिक बैंक, शहरी सहकारी बैंक, गैर-बैंकिंग वित्तीय कंपनियाँ और भुगतान प्रणाली प्रतिभागियों की सेवाओं में कमी से संबंधित किसी भी शिकायत को दर्ज करने की सुविधा प्रदान करती है।',
      'faq.q2': 'मैं अपनी शिकायत की स्थिति कैसे ट्रैक कर सकता हूँ?',
      'faq.a2': 'आप "शिकायत ट्रैक करें" पर क्लिक करके और अपना शिकायत संदर्भ नंबर दर्ज करके अपनी शिकायत की स्थिति ट्रैक कर सकते हैं। आप वर्तमान स्थिति और समीक्षा प्राधिकरण की टिप्पणियाँ देख पाएंगे।',
      'faq.q3': 'शिकायत के समाधान की समय सीमा क्या है?',
      'faq.a3': 'विनियमित संस्था को शिकायत प्राप्त होने के 30 दिनों के भीतर समाधान करना आवश्यक है। यदि आप समाधान से संतुष्ट नहीं हैं या 30 दिनों के भीतर शिकायत का समाधान नहीं होता है, तो आप इस पोर्टल पर शिकायत दर्ज कर सकते हैं।',

      // Dashboard
      'dashboard.home': 'होम',
      'dashboard.fileNew': 'नई शिकायत दर्ज करें',
      'dashboard.history': 'शिकायत इतिहास',
      'dashboard.id': 'आईडी',
      'dashboard.against': 'किसके खिलाफ',
      'dashboard.date': 'शिकायत तिथि',
      'dashboard.status': 'स्थिति',
      'dashboard.comments': 'टिप्पणियाँ',
      'dashboard.action': 'कार्रवाई',
      'dashboard.withdraw': 'वापस लें',
      'dashboard.appeal': 'अपील',
      'dashboard.act': 'कार्य करें',

      // File Complaint
      'file.title': 'शिकायत दर्ज करें',
      'file.step1': 'अपने बारे में बताएं',
      'file.step2': 'संस्था विवरण',
      'file.step3': 'अंतिम चरण: शिकायत साझा करें',
      'file.next': 'अगला',
      'file.previous': 'पिछला',
      'file.submit': 'जमा करें',

      // Track
      'track.title': 'अपनी शिकायत ट्रैक करें',
      'track.placeholder': 'शिकायत नंबर दर्ज करें',
      'track.search': 'खोजें',

      // Common
      'common.search': 'खोजें',
      'common.cancel': 'रद्द करें',
      'common.close': 'बंद करें',
      'common.loading': 'लोड हो रहा है...',
    },

    ta: {
      'header.brandHindi': 'புகார் மேலாண்மை அமைப்பு',
      'header.brandEnglish': 'புகார் மேலாண்மை அமைப்பு',
      'header.home': 'முகப்பு',
      'header.aboutUs': 'எங்களைப் பற்றி',
      'header.publicAwareness': 'பொது விழிப்புணர்வு',
      'header.contact': 'தொடர்பு',
      'header.physicalFiling': 'நேரடி புகார்',
      'header.lastSignedIn': 'கடைசி உள்நுழைவு',
      'hero.title': 'RBI க்கு உங்கள் புகார்',
      'hero.titleHighlight': 'நம்பிக்கையுடன்',
      'hero.subtitle': 'புகார் தீர்வுக்கான உங்கள் நம்பகமான தளம் - ஒழுங்குபடுத்தப்பட்ட நிறுவனங்களுக்கு எதிராக எளிதாக புகார் பதிவு செய்து கண்காணிக்கவும்.',
      'hero.fileComplaint': 'புகார் பதிவு செய்',
      'hero.alreadyFiled': 'ஏற்கனவே புகார் செய்தீர்களா?',
      'hero.trackOrWithdraw': 'புகார் கண்காணி/திரும்பப் பெறு',
      'hero.fileAppeal': 'மேல்முறையீடு',
      'hero.shareFeedback': 'கருத்து பகிர்',
      'hero.emailSimulation': 'மின்னஞ்சல் உருவகப்படுத்தல்',
      'hero.needHelp': 'உதவி வேண்டுமா?',
      'ct.findInstitution': 'உங்கள் நிதி நிறுவனத்தைக் கண்டறியுங்கள்',
      'ct.title': 'நீங்கள் இவற்றைப் பற்றி புகார் செய்யலாம்',
      'ct.searchPlaceholder': 'நிறுவனத்தைத் தேடு',
      'ct.searchHint': 'தேட விரும்பும் வங்கி அல்லது நிதி நிறுவனத்தின் பெயர் உள்ளிடவும்',
      'ct.allBanks': 'அனைத்து வணிக வங்கிகள்',
      'ct.nbfc': 'வங்கி சாரா நிதி நிறுவனங்கள்',
      'ct.creditInfo': 'கடன் தகவல் நிறுவனங்கள்',
      'ct.paymentSystem': 'கட்டண முறை பங்கேற்பாளர்கள்',
      'whatwedo.tag': 'நாங்கள் என்ன செய்கிறோம்',
      'whatwedo.title': 'இந்திய குடிமக்களுக்கான புகார் தீர்வு செயல்முறையை RBI எளிதாக்குகிறது.',
      'whatwedo.desc': 'RBI இந்திய குடிமக்களுக்கான புகார் தீர்வு செயல்முறையை எளிமையாக்கி விரைவுபடுத்துகிறது.',
      'whatwedo.howToFile': 'புகார் எப்படி பதிவு செய்வது',
      'whatwedo.whatWeCanHelp': 'நாங்கள் எதில் உதவ முடியும்',
      'stats.tag': 'புள்ளிவிவரங்கள்',
      'stats.received': 'புகார்கள் பெறப்பட்டன',
      'stats.handled': 'புகார்கள் கையாளப்பட்டன',
      'stats.resolved': 'புகார்கள் தீர்க்கப்பட்டன',
      'stats.receivedValue': '9,50,000',
      'stats.handledValue': '8,75,000',
      'stats.resolvedValue': '96%',
      'press.title': 'செய்தி வெளியீடு',
      'press.viewAll': 'அனைத்தும் காண',
      'press.readMore': 'மேலும் படிக்க',
      'press.month1': 'மார் 22',
      'press.title1': 'BE(A)WARE – நிதி மோசடிகளின் செயல்முறை குறித்த கையேடு',
      'press.desc1': 'ரிசர்வ் வங்கி இன்று "BE(A)WARE" கையேட்டை வெளியிட்டுள்ளது, இது மோசடி செய்பவர்களின் பொதுவான செயல்முறை மற்றும் நிதி பரிவர்த்தனைகளின் போது எடுக்க வேண்டிய முன்னெச்சரிக்கைகள் பற்றியது.',
      'press.month2': 'பிப் 22',
      'press.title2': 'RBI தனது பெயரில் போலி இணையதளங்கள் குறித்து எச்சரிக்கை',
      'press.desc2': 'ரிசர்வ் வங்கி தனது பெயரில் உள்ள போலி இணையதளங்கள் பற்றி பொதுமக்களை எச்சரித்துள்ளது.',
      'edu.tag': 'பொது விழிப்புணர்வு',
      'edu.title': 'கல்வி மற்றும் விழிப்புணர்வு',
      'edu.watch': 'பார்',
      'edu.read': 'படி',
      'edu.card1Title': 'அடிப்படை சேமிப்பு வங்கி வைப்பு கணக்கு (BSBDA)',
      'edu.card1Subtitle': 'அடிப்படை சேமிப்பு வங்கி வைப்பு கணக்கு BSBDA',
      'edu.card2Title': 'அங்கீகரிக்கப்படாத மின்னணு வங்கி பரிவர்த்தனைகளில் வாடிக்கையாளர் பொறுப்பு',
      'edu.card2Subtitle': 'அங்கீகரிக்கப்படாத மின்னணு வங்கி பரிவர்த்தனைகளில் வாடிக்கையாளர் பொறுப்பு',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'நிதி மோசடி செய்பவர்களின் செயல்முறை குறித்த கையேடு',
      'edu.card4Title': 'அங்கீகரிக்கப்படாத மின்னணு வங்கி பரிவர்த்தனைகளில் வாடிக்கையாளர் பொறுப்பு',
      'edu.card4Subtitle': 'அடிப்படை சேமிப்பு வங்கி வைப்பு கணக்கு BSBDA',
      'faq.tag': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'faq.title': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'faq.q1': 'இந்த இணையதளம் மூலம் என்ன வகையான புகார்களை நான் பதிவு செய்யலாம்?',
      'faq.a1': 'இந்த இணையதளம் இந்திய ரிசர்வ் வங்கியால் ஒழுங்குபடுத்தப்பட்ட வணிக வங்கிகள், நகர்ப்புற கூட்டுறவு வங்கிகள், வங்கி சாரா நிதி நிறுவனங்கள் மற்றும் கட்டண முறை பங்கேற்பாளர்களின் சேவைக் குறைபாடுகள் தொடர்பான புகார்களை பதிவு செய்ய உதவுகிறது.',
      'faq.q2': 'என் புகாரின் நிலையை எவ்வாறு கண்காணிப்பது?',
      'faq.a2': '"புகார் கண்காணி" என்பதைக் கிளிக் செய்து உங்கள் புகார் குறிப்பு எண்ணை உள்ளிட்டு நிலையை கண்காணிக்கலாம்.',
      'faq.q3': 'புகாரை தீர்க்க கால அவகாசம் என்ன?',
      'faq.a3': 'ஒழுங்குபடுத்தப்பட்ட நிறுவனம் புகார் பெற்ற 30 நாட்களுக்குள் தீர்க்க வேண்டும். திருப்தி இல்லையெனில் இந்த போர்ட்டலில் புகார் செய்யலாம்.',
      'dashboard.home': 'முகப்பு',
      'dashboard.fileNew': 'புதிய புகார் பதிவு செய்',
      'dashboard.history': 'புகார் வரலாறு',
      'dashboard.id': 'எண்',
      'dashboard.against': 'யாருக்கு எதிராக',
      'dashboard.date': 'புகார் தேதி',
      'dashboard.status': 'நிலை',
      'dashboard.comments': 'கருத்துகள்',
      'dashboard.action': 'நடவடிக்கை',
      'dashboard.withdraw': 'திரும்பப் பெறு',
      'dashboard.appeal': 'மேல்முறையீடு',
      'dashboard.act': 'நடவடிக்கை',
      'file.title': 'புகார் பதிவு செய்',
      'file.next': 'அடுத்து',
      'file.previous': 'முந்தைய',
      'file.submit': 'சமர்ப்பி',
      'track.title': 'உங்கள் புகாரைக் கண்காணிக்கவும்',
      'track.placeholder': 'புகார் எண் உள்ளிடவும்',
      'track.search': 'தேடு',
      'common.search': 'தேடு',
      'common.cancel': 'ரத்து',
      'common.close': 'மூடு',
      'common.loading': 'ஏற்றுகிறது...',
    },

    te: {
      'header.brandHindi': 'ఫిర్యాదు నిర్వహణ వ్యవస్థ',
      'header.brandEnglish': 'ఫిర్యాదు నిర్వహణ వ్యవస్థ',
      'header.home': 'హోమ్',
      'header.aboutUs': 'మా గురించి',
      'header.publicAwareness': 'ప్రజా అవగాహన',
      'header.contact': 'సంప్రదించండి',
      'header.physicalFiling': 'భౌతిక ఫిర్యాదు',
      'header.lastSignedIn': 'చివరి లాగిన్',
      'hero.title': 'RBI కి మీ ఫిర్యాదు',
      'hero.titleHighlight': 'నమ్మకంతో',
      'hero.subtitle': 'ఫిర్యాదు పరిష్కారానికి మీ నమ్మకమైన వేదిక - నియంత్రిత సంస్థలపై సులభంగా ఫిర్యాదులు దాఖలు చేసి ట్రాక్ చేయండి.',
      'hero.fileComplaint': 'ఫిర్యాదు దాఖలు చేయండి',
      'hero.alreadyFiled': 'ఇప్పటికే ఫిర్యాదు చేశారా?',
      'hero.trackOrWithdraw': 'ఫిర్యాదు ట్రాక్/ఉపసంహరించు',
      'hero.fileAppeal': 'అప్పీల్ దాఖలు',
      'hero.shareFeedback': 'మీ అభిప్రాయం పంచండి',
      'hero.emailSimulation': 'ఇమెయిల్ సిమ్యులేషన్',
      'hero.needHelp': 'సహాయం కావాలా?',
      'ct.findInstitution': 'మీ ఆర్థిక సంస్థను కనుగొనండి',
      'ct.title': 'మీరు వీటి గురించి ఫిర్యాదు చేయవచ్చు',
      'ct.searchPlaceholder': 'సంస్థను వెతకండి',
      'ct.searchHint': 'మీరు వెతకాలనుకుంటున్న బ్యాంక్ లేదా ఆర్థిక సంస్థ పేరు నమోదు చేయండి',
      'ct.allBanks': 'అన్ని వాణిజ్య బ్యాంకులు',
      'ct.nbfc': 'బ్యాంకేతర ఆర్థిక సంస్థలు',
      'ct.creditInfo': 'క్రెడిట్ సమాచార సంస్థలు',
      'ct.paymentSystem': 'చెల్లింపు వ్యవస్థ భాగస్వాములు',
      'whatwedo.tag': 'మేము ఏమి చేస్తాము',
      'whatwedo.title': 'RBI భారత పౌరులకు ఫిర్యాదు పరిష్కార ప్రక్రియను సరళీకరిస్తుంది.',
      'whatwedo.desc': 'RBI భారత పౌరులకు ఫిర్యాదు పరిష్కార ప్రక్రియను సరళీకరించి వేగవంతం చేస్తుంది.',
      'whatwedo.howToFile': 'ఫిర్యాదు ఎలా దాఖలు చేయాలి',
      'whatwedo.whatWeCanHelp': 'మేము ఏమి సహాయం చేయగలము',
      'stats.tag': 'గణాంకాలు',
      'stats.received': 'ఫిర్యాదులు అందాయి',
      'stats.handled': 'ఫిర్యాదులు నిర్వహించబడ్డాయి',
      'stats.resolved': 'ఫిర్యాదులు పరిష్కరించబడ్డాయి',
      'stats.receivedValue': '9,50,000',
      'stats.handledValue': '8,75,000',
      'stats.resolvedValue': '96%',
      'press.title': 'ప్రెస్ విడుదల',
      'press.viewAll': 'అన్నీ చూడండి',
      'press.readMore': 'మరింత చదవండి',
      'press.month1': 'మార్చి 22',
      'press.title1': 'BE(A)WARE – ఆర్థిక మోసాల కార్యవిధానంపై పుస్తకం',
      'press.desc1': 'రిజర్వ్ బ్యాంక్ ఈ రోజు "BE(A)WARE" పుస్తకాన్ని విడుదల చేసింది, ఇది మోసగాళ్ల సాధారణ కార్యవిధానం మరియు ఆర్థిక లావాదేవీలు చేసేటప్పుడు తీసుకోవాల్సిన జాగ్రత్తలపై ఆధారపడినది.',
      'press.month2': 'ఫిబ్ర 22',
      'press.title2': 'RBI తన పేరుతో నకిలీ వెబ్‌సైట్ల గురించి హెచ్చరిక',
      'press.desc2': 'రిజర్వ్ బ్యాంక్ తన పేరుతో ఉన్న నకిలీ వెబ్‌సైట్ల గురించి ప్రజలను హెచ్చరించింది.',
      'edu.tag': 'ప్రజా అవగాహన',
      'edu.title': 'విద్య మరియు అవగాహన',
      'edu.watch': 'చూడండి',
      'edu.read': 'చదవండి',
      'edu.card1Title': 'బేసిక్ సేవింగ్స్ బ్యాంక్ డిపాజిట్ ఖాతా (BSBDA)',
      'edu.card1Subtitle': 'బేసిక్ సేవింగ్స్ బ్యాంక్ డిపాజిట్ ఖాతా BSBDA',
      'edu.card2Title': 'అనధికార ఎలక్ట్రానిక్ బ్యాంకింగ్ లావాదేవీలలో కస్టమర్ బాధ్యత',
      'edu.card2Subtitle': 'అనధికార ఎలక్ట్రానిక్ బ్యాంకింగ్ లావాదేవీలలో కస్టమర్ బాధ్యత',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'ఆర్థిక మోసగాళ్ల కార్యవిధానంపై పుస్తకం',
      'edu.card4Title': 'అనధికార ఎలక్ట్రానిక్ బ్యాంకింగ్ లావాదేవీలలో కస్టమర్ బాధ్యత',
      'edu.card4Subtitle': 'బేసిక్ సేవింగ్స్ బ్యాంక్ డిపాజిట్ ఖాతా BSBDA',
      'faq.tag': 'తరచుగా అడిగే ప్రశ్నలు',
      'faq.title': 'తరచుగా అడిగే ప్రశ్నలు',
      'faq.q1': 'ఈ వెబ్‌సైట్ ద్వారా నేను ఏ రకమైన ఫిర్యాదులు దాఖలు చేయవచ్చు?',
      'faq.a1': 'ఈ వెబ్‌సైట్ భారతీయ రిజర్వ్ బ్యాంక్ నియంత్రిత వాణిజ్య బ్యాంకులు, పట్టణ సహకార బ్యాంకులు, బ్యాంకేతర ఆర్థిక సంస్థలు మరియు చెల్లింపు వ్యవస్థ భాగస్వాముల సేవా లోపాలకు సంబంధించిన ఫిర్యాదులను దాఖలు చేయడానికి సహాయపడుతుంది.',
      'faq.q2': 'నా ఫిర్యాదు స్థితిని ఎలా ట్రాక్ చేయాలి?',
      'faq.a2': '"ఫిర్యాదు ట్రాక్" క్లిక్ చేసి మీ ఫిర్యాదు సంఖ్యను నమోదు చేయడం ద్వారా స్థితిని తెలుసుకోవచ్చు.',
      'faq.q3': 'ఫిర్యాదు పరిష్కారానికి సమయ పరిమితి ఏమిటి?',
      'faq.a3': 'నియంత్రిత సంస్థ ఫిర్యాదు అందుకున్న 30 రోజులలోపు పరిష్కరించాలి. సంతృప్తి లేకపోతే ఈ పోర్టల్‌లో ఫిర్యాదు చేయవచ్చు.',
      'dashboard.home': 'హోమ్',
      'dashboard.fileNew': 'కొత్త ఫిర్యాదు దాఖలు',
      'dashboard.history': 'ఫిర్యాదు చరిత్ర',
      'dashboard.id': 'ఐడి',
      'dashboard.against': 'ఎవరిపై',
      'dashboard.date': 'ఫిర్యాదు తేదీ',
      'dashboard.status': 'స్థితి',
      'dashboard.comments': 'వ్యాఖ్యలు',
      'dashboard.action': 'చర్య',
      'dashboard.withdraw': 'ఉపసంహరించు',
      'dashboard.appeal': 'అప్పీల్',
      'dashboard.act': 'చర్య',
      'file.title': 'ఫిర్యాదు దాఖలు',
      'file.next': 'తదుపరి',
      'file.previous': 'మునుపటి',
      'file.submit': 'సమర్పించు',
      'track.title': 'మీ ఫిర్యాదును ట్రాక్ చేయండి',
      'track.placeholder': 'ఫిర్యాదు నంబర్ నమోదు చేయండి',
      'track.search': 'వెతకండి',
      'common.search': 'వెతకండి',
      'common.cancel': 'రద్దు',
      'common.close': 'మూసివేయి',
      'common.loading': 'లోడ్ అవుతోంది...',
    },

    bn: {
      'header.brandHindi': 'অভিযোগ ব্যবস্থাপনা সিস্টেম',
      'header.brandEnglish': 'অভিযোগ ব্যবস্থাপনা সিস্টেম',
      'header.home': 'হোম',
      'header.aboutUs': 'আমাদের সম্পর্কে',
      'header.publicAwareness': 'জনসচেতনতা',
      'header.contact': 'যোগাযোগ',
      'header.physicalFiling': 'ভৌত অভিযোগ',
      'header.lastSignedIn': 'শেষ লগইন',
      'hero.title': 'RBI-তে আপনার অভিযোগ',
      'hero.titleHighlight': 'আত্মবিশ্বাসের সাথে',
      'hero.subtitle': 'অভিযোগ সমাধানের জন্য আপনার বিশ্বস্ত প্ল্যাটফর্ম - নিয়ন্ত্রিত সংস্থাগুলির বিরুদ্ধে সহজে অভিযোগ দায়ের করুন এবং ট্র্যাক করুন।',
      'hero.fileComplaint': 'অভিযোগ দায়ের করুন',
      'hero.alreadyFiled': 'ইতিমধ্যে অভিযোগ করেছেন?',
      'hero.trackOrWithdraw': 'অভিযোগ ট্র্যাক/প্রত্যাহার',
      'hero.fileAppeal': 'আপিল দায়ের',
      'hero.shareFeedback': 'মতামত জানান',
      'hero.emailSimulation': 'ইমেল সিমুলেশন',
      'hero.needHelp': 'সাহায্য দরকার?',
      'ct.findInstitution': 'আপনার আর্থিক প্রতিষ্ঠান খুঁজুন',
      'ct.title': 'আপনি এদের সম্পর্কে অভিযোগ করতে পারেন',
      'ct.searchPlaceholder': 'প্রতিষ্ঠান খুঁজুন',
      'ct.searchHint': 'যে ব্যাংক বা আর্থিক প্রতিষ্ঠান খুঁজতে চান তার নাম লিখুন',
      'ct.allBanks': 'সকল বাণিজ্যিক ব্যাংক',
      'ct.nbfc': 'নন-ব্যাংকিং আর্থিক কোম্পানি',
      'ct.creditInfo': 'ক্রেডিট তথ্য কোম্পানি',
      'ct.paymentSystem': 'পেমেন্ট সিস্টেম অংশগ্রহণকারী',
      'whatwedo.tag': 'আমরা কী করি',
      'whatwedo.title': 'RBI ভারতীয় নাগরিকদের জন্য অভিযোগ সমাধান প্রক্রিয়া সহজ করে।',
      'whatwedo.desc': 'RBI ভারতীয় নাগরিকদের জন্য অভিযোগ সমাধান প্রক্রিয়া সরলীকরণ ও ত্বরান্বিত করে।',
      'whatwedo.howToFile': 'কিভাবে অভিযোগ করবেন',
      'whatwedo.whatWeCanHelp': 'আমরা কিসে সাহায্য করতে পারি',
      'stats.tag': 'পরিসংখ্যান',
      'stats.received': 'অভিযোগ প্রাপ্ত',
      'stats.handled': 'অভিযোগ পরিচালিত',
      'stats.resolved': 'অভিযোগ সমাধান',
      'stats.receivedValue': '৯,৫০,০০০',
      'stats.handledValue': '৮,৭৫,০০০',
      'stats.resolvedValue': '৯৬%',
      'press.title': 'প্রেস বিজ্ঞপ্তি',
      'press.viewAll': 'সব দেখুন',
      'press.readMore': 'আরও পড়ুন',
      'press.month1': 'মার্চ ২২',
      'press.title1': 'BE(A)WARE – আর্থিক জালিয়াতির কার্যপদ্ধতি সম্পর্কিত পুস্তিকা',
      'press.desc1': 'রিজার্ভ ব্যাংক আজ "BE(A)WARE" পুস্তিকা প্রকাশ করেছে যা জালিয়াতদের সাধারণ কার্যপদ্ধতি এবং আর্থিক লেনদেনের সময় সাবধানতা সম্পর্কে।',
      'press.month2': 'ফেব্র ২২',
      'press.title2': 'RBI তার নামে ভুয়া ওয়েবসাইট সম্পর্কে সতর্কতা',
      'press.desc2': 'রিজার্ভ ব্যাংক জনসাধারণকে তার নামে ভুয়া ওয়েবসাইট সম্পর্কে সতর্ক করেছে।',
      'edu.tag': 'জনসচেতনতা',
      'edu.title': 'শিক্ষা ও সচেতনতা',
      'edu.watch': 'দেখুন',
      'edu.read': 'পড়ুন',
      'edu.card1Title': 'বেসিক সেভিংস ব্যাংক ডিপোজিট অ্যাকাউন্ট (BSBDA)',
      'edu.card1Subtitle': 'বেসিক সেভিংস ব্যাংক ডিপোজিট অ্যাকাউন্ট BSBDA',
      'edu.card2Title': 'অননুমোদিত ইলেকট্রনিক ব্যাংকিং লেনদেনে গ্রাহক দায়',
      'edu.card2Subtitle': 'অননুমোদিত ইলেকট্রনিক ব্যাংকিং লেনদেনে গ্রাহক দায়',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'আর্থিক জালিয়াতদের কার্যপদ্ধতি সম্পর্কিত পুস্তিকা',
      'edu.card4Title': 'অননুমোদিত ইলেকট্রনিক ব্যাংকিং লেনদেনে গ্রাহক দায়',
      'edu.card4Subtitle': 'বেসিক সেভিংস ব্যাংক ডিপোজিট অ্যাকাউন্ট BSBDA',
      'faq.tag': 'সচরাচর জিজ্ঞাসা',
      'faq.title': 'সচরাচর জিজ্ঞাসিত প্রশ্নাবলী',
      'faq.q1': 'এই ওয়েবসাইটের মাধ্যমে আমি কী ধরনের অভিযোগ দায়ের করতে পারি?',
      'faq.a1': 'এই ওয়েবসাইটটি ভারতীয় রিজার্ভ ব্যাংক দ্বারা নিয়ন্ত্রিত বাণিজ্যিক ব্যাংক, শহুরে সমবায় ব্যাংক, নন-ব্যাংকিং আর্থিক কোম্পানি এবং পেমেন্ট সিস্টেম অংশগ্রহণকারীদের সেবার ঘাটতি সম্পর্কিত অভিযোগ দায়ের করতে সাহায্য করে।',
      'faq.q2': 'আমি কিভাবে আমার অভিযোগের অবস্থা ট্র্যাক করতে পারি?',
      'faq.a2': '"অভিযোগ ট্র্যাক করুন" ক্লিক করে আপনার অভিযোগ রেফারেন্স নম্বর দিয়ে অবস্থা জানতে পারবেন।',
      'faq.q3': 'অভিযোগ সমাধানের সময়সীমা কত?',
      'faq.a3': 'নিয়ন্ত্রিত সংস্থাকে অভিযোগ পাওয়ার ৩০ দিনের মধ্যে সমাধান করতে হবে। সন্তুষ্ট না হলে এই পোর্টালে অভিযোগ করতে পারেন।',
      'dashboard.home': 'হোম',
      'dashboard.fileNew': 'নতুন অভিযোগ দায়ের',
      'dashboard.history': 'অভিযোগের ইতিহাস',
      'dashboard.id': 'আইডি',
      'dashboard.against': 'কার বিরুদ্ধে',
      'dashboard.date': 'অভিযোগের তারিখ',
      'dashboard.status': 'অবস্থা',
      'dashboard.comments': 'মন্তব্য',
      'dashboard.action': 'পদক্ষেপ',
      'dashboard.withdraw': 'প্রত্যাহার',
      'dashboard.appeal': 'আপিল',
      'dashboard.act': 'পদক্ষেপ',
      'file.title': 'অভিযোগ দায়ের করুন',
      'file.next': 'পরবর্তী',
      'file.previous': 'পূর্ববর্তী',
      'file.submit': 'জমা দিন',
      'track.title': 'আপনার অভিযোগ ট্র্যাক করুন',
      'track.placeholder': 'অভিযোগ নম্বর লিখুন',
      'track.search': 'খুঁজুন',
      'common.search': 'খুঁজুন',
      'common.cancel': 'বাতিল',
      'common.close': 'বন্ধ',
      'common.loading': 'লোড হচ্ছে...',
    },

    mr: {
      'header.brandHindi': 'तक्रार व्यवस्थापन प्रणाली',
      'header.brandEnglish': 'तक्रार व्यवस्थापन प्रणाली',
      'header.home': 'मुखपृष्ठ',
      'header.aboutUs': 'आमच्याबद्दल',
      'header.publicAwareness': 'जनजागृती',
      'header.contact': 'संपर्क',
      'header.physicalFiling': 'भौतिक तक्रार',
      'header.lastSignedIn': 'शेवटचे लॉगिन',
      'hero.title': 'RBI ला तुमची तक्रार',
      'hero.titleHighlight': 'आत्मविश्वासाने',
      'hero.subtitle': 'तक्रार निवारणासाठी तुमचे विश्वसनीय व्यासपीठ - नियमित संस्थांविरुद्ध सहज तक्रार नोंदवा आणि मागोवा घ्या.',
      'hero.fileComplaint': 'तक्रार नोंदवा',
      'hero.alreadyFiled': 'आधीच तक्रार केली आहे?',
      'hero.trackOrWithdraw': 'तक्रार मागोवा/मागे घ्या',
      'hero.fileAppeal': 'अपील दाखल करा',
      'hero.shareFeedback': 'अभिप्राय द्या',
      'hero.emailSimulation': 'ईमेल सिम्युलेशन',
      'hero.needHelp': 'मदत हवी?',
      'ct.findInstitution': 'तुमची वित्तीय संस्था शोधा',
      'ct.title': 'तुम्ही यांच्याबद्दल तक्रार करू शकता',
      'ct.searchPlaceholder': 'संस्था शोधा',
      'ct.searchHint': 'शोधायच्या बँक किंवा वित्तीय संस्थेचे नाव प्रविष्ट करा',
      'ct.allBanks': 'सर्व व्यापारी बँका',
      'ct.nbfc': 'बिगर-बँकिंग वित्तीय कंपन्या',
      'ct.creditInfo': 'क्रेडिट माहिती कंपन्या',
      'ct.paymentSystem': 'पेमेंट सिस्टम सहभागी',
      'whatwedo.tag': 'आम्ही काय करतो',
      'whatwedo.title': 'RBI भारतीय नागरिकांसाठी तक्रार निवारण प्रक्रिया सुलभ करते.',
      'whatwedo.desc': 'RBI भारतीय नागरिकांसाठी तक्रार निवारण प्रक्रिया सरल आणि जलद करते.',
      'whatwedo.howToFile': 'तक्रार कशी नोंदवावी',
      'whatwedo.whatWeCanHelp': 'आम्ही काय मदत करू शकतो',
      'stats.tag': 'आकडेवारी',
      'stats.received': 'तक्रारी प्राप्त',
      'stats.handled': 'तक्रारी हाताळल्या',
      'stats.resolved': 'तक्रारी सोडवल्या',
      'stats.receivedValue': '९,५०,०००',
      'stats.handledValue': '८,७५,०००',
      'stats.resolvedValue': '९६%',
      'press.title': 'प्रेस प्रकाशन',
      'press.viewAll': 'सर्व पहा',
      'press.readMore': 'अधिक वाचा',
      'press.month1': 'मार्च २२',
      'press.title1': 'BE(A)WARE – आर्थिक फसवणुकीच्या कार्यपद्धतीवर पुस्तिका',
      'press.desc1': 'रिझर्व्ह बँकेने आज "BE(A)WARE" पुस्तिका प्रसिद्ध केली आहे जी फसवणूक करणाऱ्यांची सामान्य कार्यपद्धती आणि आर्थिक व्यवहार करताना घ्यावयाची काळजी याबद्दल आहे.',
      'press.month2': 'फेब्रु २२',
      'press.title2': 'RBI ने आपल्या नावावर बनावट वेबसाइटबद्दल सावध केले',
      'press.desc2': 'रिझर्व्ह बँकेने जनतेला आपल्या नावावरील बनावट वेबसाइटबद्दल सावध केले आहे.',
      'edu.tag': 'जनजागृती',
      'edu.title': 'शिक्षण आणि जागृती',
      'edu.watch': 'पहा',
      'edu.read': 'वाचा',
      'edu.card1Title': 'मूलभूत बचत बँक ठेव खाते (BSBDA)',
      'edu.card1Subtitle': 'मूलभूत बचत बँक ठेव खाते BSBDA',
      'edu.card2Title': 'अनधिकृत इलेक्ट्रॉनिक बँकिंग व्यवहारांमध्ये ग्राहक जबाबदारी',
      'edu.card2Subtitle': 'अनधिकृत इलेक्ट्रॉनिक बँकिंग व्यवहारांमध्ये ग्राहक जबाबदारी',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'आर्थिक फसवणूक करणाऱ्यांच्या कार्यपद्धतीवर पुस्तिका',
      'edu.card4Title': 'अनधिकृत इलेक्ट्रॉनिक बँकिंग व्यवहारांमध्ये ग्राहक जबाबदारी',
      'edu.card4Subtitle': 'मूलभूत बचत बँक ठेव खाते BSBDA',
      'faq.tag': 'वारंवार विचारले जाणारे प्रश्न',
      'faq.title': 'वारंवार विचारले जाणारे प्रश्न',
      'faq.q1': 'या वेबसाइटद्वारे मी कोणत्या प्रकारच्या तक्रारी नोंदवू शकतो?',
      'faq.a1': 'ही वेबसाइट भारतीय रिझर्व्ह बँकेने नियमन केलेल्या व्यापारी बँका, शहरी सहकारी बँका, बिगर-बँकिंग वित्तीय कंपन्या आणि पेमेंट सिस्टम सहभागींच्या सेवा कमतरतेबद्दलच्या तक्रारी नोंदवण्यात मदत करते.',
      'faq.q2': 'मी माझ्या तक्रारीची स्थिती कशी ट्रॅक करू शकतो?',
      'faq.a2': '"तक्रार ट्रॅक करा" वर क्लिक करून आपला तक्रार संदर्भ क्रमांक टाकून स्थिती जाणून घेता येते.',
      'faq.q3': 'तक्रार निवारणासाठी कालमर्यादा किती आहे?',
      'faq.a3': 'नियमित संस्थेला तक्रार मिळाल्यापासून ३० दिवसांत निवारण करणे आवश्यक आहे. समाधान न झाल्यास या पोर्टलवर तक्रार नोंदवता येते.',
      'dashboard.home': 'मुखपृष्ठ',
      'dashboard.fileNew': 'नवीन तक्रार नोंदवा',
      'dashboard.history': 'तक्रार इतिहास',
      'dashboard.id': 'आयडी',
      'dashboard.against': 'कोणाविरुद्ध',
      'dashboard.date': 'तक्रार तारीख',
      'dashboard.status': 'स्थिती',
      'dashboard.comments': 'टिप्पण्या',
      'dashboard.action': 'कृती',
      'dashboard.withdraw': 'मागे घ्या',
      'dashboard.appeal': 'अपील',
      'dashboard.act': 'कृती',
      'file.title': 'तक्रार नोंदवा',
      'file.next': 'पुढे',
      'file.previous': 'मागे',
      'file.submit': 'सबमिट करा',
      'track.title': 'तुमची तक्रार मागोवा घ्या',
      'track.placeholder': 'तक्रार क्रमांक प्रविष्ट करा',
      'track.search': 'शोधा',
      'common.search': 'शोधा',
      'common.cancel': 'रद्द करा',
      'common.close': 'बंद करा',
      'common.loading': 'लोड होत आहे...',
    },

    gu: {
      'header.brandHindi': 'ફરિયાદ વ્યવસ્થાપન પ્રણાલી',
      'header.brandEnglish': 'ફરિયાદ વ્યવસ્થાપન પ્રણાલી',
      'header.home': 'હોમ',
      'header.aboutUs': 'અમારા વિશે',
      'header.publicAwareness': 'જન જાગૃતિ',
      'header.contact': 'સંપર્ક',
      'header.physicalFiling': 'ભૌતિક ફરિયાદ',
      'header.lastSignedIn': 'છેલ્લું લૉગિન',
      'hero.title': 'RBI ને તમારી ફરિયાદ',
      'hero.titleHighlight': 'વિશ્વાસ સાથે',
      'hero.subtitle': 'ફરિયાદ નિવારણ માટે તમારું વિશ્વસનીય પ્લેટફોર્મ - નિયમિત સંસ્થાઓ વિરુદ્ધ સરળતાથી ફરિયાદ નોંધાવો અને ટ્રૅક કરો.',
      'hero.fileComplaint': 'ફરિયાદ નોંધાવો',
      'hero.alreadyFiled': 'પહેલેથી ફરિયાદ કરી છે?',
      'hero.trackOrWithdraw': 'ફરિયાદ ટ્રૅક/પાછી ખેંચો',
      'hero.fileAppeal': 'અપીલ દાખલ કરો',
      'hero.shareFeedback': 'પ્રતિસાદ આપો',
      'hero.emailSimulation': 'ઈમેલ સિમ્યુલેશન',
      'hero.needHelp': 'મદદ જોઈએ?',
      'ct.findInstitution': 'તમારી નાણાકીય સંસ્થા શોધો',
      'ct.title': 'તમે આ વિશે ફરિયાદ કરી શકો છો',
      'ct.searchPlaceholder': 'સંસ્થા શોધો',
      'ct.searchHint': 'શોધવા માંગતા બેંક અથવા નાણાકીય સંસ્થાનું નામ દાખલ કરો',
      'ct.allBanks': 'તમામ વ્યાપારી બેંકો',
      'ct.nbfc': 'બિન-બેંકિંગ નાણાકીય કંપનીઓ',
      'ct.creditInfo': 'ક્રેડિટ માહિતી કંપનીઓ',
      'ct.paymentSystem': 'ચુકવણી પ્રણાલી સહભાગીઓ',
      'whatwedo.tag': 'અમે શું કરીએ છીએ',
      'whatwedo.title': 'RBI ભારતીય નાગરિકો માટે ફરિયાદ નિવારણ પ્રક્રિયા સરળ બનાવે છે.',
      'whatwedo.desc': 'RBI ભારતીય નાગરિકો માટે ફરિયાદ નિવારણ પ્રક્રિયા સરળ અને ઝડપી બનાવે છે.',
      'whatwedo.howToFile': 'ફરિયાદ કેવી રીતે નોંધાવવી',
      'whatwedo.whatWeCanHelp': 'અમે શું મદદ કરી શકીએ',
      'stats.tag': 'આંકડા',
      'stats.received': 'ફરિયાદો પ્રાપ્ત',
      'stats.handled': 'ફરિયાદો સંભાળી',
      'stats.resolved': 'ફરિયાદો ઉકેલાઈ',
      'stats.receivedValue': '૯,૫૦,૦૦૦',
      'stats.handledValue': '૮,૭૫,૦૦૦',
      'stats.resolvedValue': '૯૬%',
      'press.title': 'પ્રેસ રિલીઝ',
      'press.viewAll': 'બધું જુઓ',
      'press.readMore': 'વધુ વાંચો',
      'press.month1': 'માર્ચ ૨૨',
      'press.title1': 'BE(A)WARE – નાણાકીય છેતરપિંડીની કાર્યપદ્ધતિ પર પુસ્તિકા',
      'press.desc1': 'રિઝર્વ બેંકે આજે "BE(A)WARE" પુસ્તિકા પ્રકાશિત કરી છે જે છેતરપિંડી કરનારાઓની સામાન્ય કાર્યપદ્ધતિ અને નાણાકીય વ્યવહાર કરતી વખતે રાખવાની સાવધાની વિશે છે.',
      'press.month2': 'ફેબ્રુ ૨૨',
      'press.title2': 'RBI એ પોતાના નામે બનાવટી વેબસાઈટ વિશે ચેતવણી આપી',
      'press.desc2': 'રિઝર્વ બેંકે જનતાને પોતાના નામે બનાવટી વેબસાઈટ વિશે સાવધાન કરી છે.',
      'edu.tag': 'જન જાગૃતિ',
      'edu.title': 'શિક્ષણ અને જાગૃતિ',
      'edu.watch': 'જુઓ',
      'edu.read': 'વાંચો',
      'edu.card1Title': 'બેસિક સેવિંગ્સ બેંક ડિપોઝિટ એકાઉન્ટ (BSBDA)',
      'edu.card1Subtitle': 'બેસિક સેવિંગ્સ બેંક ડિપોઝિટ એકાઉન્ટ BSBDA',
      'edu.card2Title': 'અનધિકૃત ઇલેક્ટ્રોનિક બેંકિંગ વ્યવહારોમાં ગ્રાહક જવાબદારી',
      'edu.card2Subtitle': 'અનધિકૃત ઇલેક્ટ્રોનિક બેંકિંગ વ્યવહારોમાં ગ્રાહક જવાબદારી',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'નાણાકીય છેતરપિંડી કરનારાઓની કાર્યપદ્ધતિ પર પુસ્તિકા',
      'edu.card4Title': 'અનધિકૃત ઇલેક્ટ્રોનિક બેંકિંગ વ્યવહારોમાં ગ્રાહક જવાબદારી',
      'edu.card4Subtitle': 'બેસિક સેવિંગ્સ બેંક ડિપોઝિટ એકાઉન્ટ BSBDA',
      'faq.tag': 'વારંવાર પૂછાતા પ્રશ્નો',
      'faq.title': 'વારંવાર પૂછાતા પ્રશ્નો',
      'faq.q1': 'આ વેબસાઈટ દ્વારા હું કયા પ્રકારની ફરિયાદો નોંધાવી શકું?',
      'faq.a1': 'આ વેબસાઈટ ભારતીય રિઝર્વ બેંક દ્વારા નિયમિત વ્યાપારી બેંકો, શહેરી સહકારી બેંકો, બિન-બેંકિંગ નાણાકીય કંપનીઓ અને ચુકવણી પ્રણાલી સહભાગીઓની સેવા ખામી અંગેની ફરિયાદો નોંધાવવામાં મદદ કરે છે.',
      'faq.q2': 'હું મારી ફરિયાદની સ્થિતિ કેવી રીતે ટ્રૅક કરું?',
      'faq.a2': '"ફરિયાદ ટ્રૅક કરો" પર ક્લિક કરીને તમારો ફરિયાદ સંદર્ભ નંબર દાખલ કરીને સ્થિતિ જાણી શકો છો.',
      'faq.q3': 'ફરિયાદ ઉકેલવાની સમય મર્યાદા શું છે?',
      'faq.a3': 'નિયમિત સંસ્થાએ ફરિયાદ મળ્યાના ૩૦ દિવસમાં ઉકેલ આપવો જરૂરી છે. સંતોષ ન થાય તો આ પોર્ટલ પર ફરિયાદ કરી શકો છો.',
      'dashboard.home': 'હોમ',
      'dashboard.fileNew': 'નવી ફરિયાદ નોંધાવો',
      'dashboard.history': 'ફરિયાદ ઇતિહાસ',
      'dashboard.id': 'આઈડી',
      'dashboard.against': 'કોની વિરુદ્ધ',
      'dashboard.date': 'ફરિયાદ તારીખ',
      'dashboard.status': 'સ્થિતિ',
      'dashboard.comments': 'ટિપ્પણીઓ',
      'dashboard.action': 'ક્રિયા',
      'dashboard.withdraw': 'પાછી ખેંચો',
      'dashboard.appeal': 'અપીલ',
      'dashboard.act': 'ક્રિયા',
      'file.title': 'ફરિયાદ નોંધાવો',
      'file.next': 'આગળ',
      'file.previous': 'પાછળ',
      'file.submit': 'સબમિટ કરો',
      'track.title': 'તમારી ફરિયાદ ટ્રૅક કરો',
      'track.placeholder': 'ફરિયાદ નંબર દાખલ કરો',
      'track.search': 'શોધો',
      'common.search': 'શોધો',
      'common.cancel': 'રદ કરો',
      'common.close': 'બંધ',
      'common.loading': 'લોડ થઈ રહ્યું છે...',
    },

    kn: {
      'header.brandHindi': 'ದೂರು ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ',
      'header.brandEnglish': 'ದೂರು ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ',
      'header.home': 'ಮುಖಪುಟ',
      'header.aboutUs': 'ನಮ್ಮ ಬಗ್ಗೆ',
      'header.publicAwareness': 'ಸಾರ್ವಜನಿಕ ಜಾಗೃತಿ',
      'header.contact': 'ಸಂಪರ್ಕ',
      'header.physicalFiling': 'ಭೌತಿಕ ದೂರು',
      'header.lastSignedIn': 'ಕೊನೆಯ ಲಾಗಿನ್',
      'hero.title': 'RBI ಗೆ ನಿಮ್ಮ ದೂರು',
      'hero.titleHighlight': 'ವಿಶ್ವಾಸದೊಂದಿಗೆ',
      'hero.subtitle': 'ದೂರು ಪರಿಹಾರಕ್ಕೆ ನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ವೇದಿಕೆ - ನಿಯಂತ್ರಿತ ಸಂಸ್ಥೆಗಳ ವಿರುದ್ಧ ಸುಲಭವಾಗಿ ದೂರು ದಾಖಲಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
      'hero.fileComplaint': 'ದೂರು ಸಲ್ಲಿಸಿ',
      'hero.alreadyFiled': 'ಈಗಾಗಲೇ ದೂರು ನೀಡಿದ್ದೀರಾ?',
      'hero.trackOrWithdraw': 'ದೂರು ಟ್ರ್ಯಾಕ್/ಹಿಂತೆಗೆದುಕೊಳ್ಳಿ',
      'hero.fileAppeal': 'ಮೇಲ್ಮನವಿ ಸಲ್ಲಿಸಿ',
      'hero.shareFeedback': 'ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ',
      'hero.emailSimulation': 'ಇಮೇಲ್ ಸಿಮ್ಯುಲೇಶನ್',
      'hero.needHelp': 'ಸಹಾಯ ಬೇಕೇ?',
      'ct.findInstitution': 'ನಿಮ್ಮ ಹಣಕಾಸು ಸಂಸ್ಥೆ ಹುಡುಕಿ',
      'ct.title': 'ನೀವು ಇವುಗಳ ಬಗ್ಗೆ ದೂರು ನೀಡಬಹುದು',
      'ct.searchPlaceholder': 'ಸಂಸ್ಥೆ ಹುಡುಕಿ',
      'ct.searchHint': 'ಹುಡುಕಲು ಬಯಸುವ ಬ್ಯಾಂಕ್ ಅಥವಾ ಹಣಕಾಸು ಸಂಸ್ಥೆಯ ಹೆಸರು ನಮೂದಿಸಿ',
      'ct.allBanks': 'ಎಲ್ಲಾ ವಾಣಿಜ್ಯ ಬ್ಯಾಂಕ್‌ಗಳು',
      'ct.nbfc': 'ಬ್ಯಾಂಕೇತರ ಹಣಕಾಸು ಸಂಸ್ಥೆಗಳು',
      'ct.creditInfo': 'ಕ್ರೆಡಿಟ್ ಮಾಹಿತಿ ಸಂಸ್ಥೆಗಳು',
      'ct.paymentSystem': 'ಪಾವತಿ ವ್ಯವಸ್ಥೆ ಭಾಗವಹಿಸುವವರು',
      'whatwedo.tag': 'ನಾವು ಏನು ಮಾಡುತ್ತೇವೆ',
      'whatwedo.title': 'RBI ಭಾರತೀಯ ನಾಗರಿಕರಿಗೆ ದೂರು ಪರಿಹಾರ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಸರಳಗೊಳಿಸುತ್ತದೆ.',
      'whatwedo.desc': 'RBI ಭಾರತೀಯ ನಾಗರಿಕರಿಗೆ ದೂರು ಪರಿಹಾರ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಸರಳ ಮತ್ತು ವೇಗಗೊಳಿಸುತ್ತದೆ.',
      'whatwedo.howToFile': 'ದೂರು ಹೇಗೆ ಸಲ್ಲಿಸುವುದು',
      'whatwedo.whatWeCanHelp': 'ನಾವು ಏನು ಸಹಾಯ ಮಾಡಬಹುದು',
      'stats.tag': 'ಅಂಕಿಅಂಶಗಳು',
      'stats.received': 'ದೂರುಗಳು ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'stats.handled': 'ದೂರುಗಳು ನಿರ್ವಹಿಸಲಾಗಿದೆ',
      'stats.resolved': 'ದೂರುಗಳು ಪರಿಹರಿಸಲಾಗಿದೆ',
      'stats.receivedValue': '೯,೫೦,೦೦೦',
      'stats.handledValue': '೮,೭೫,೦೦೦',
      'stats.resolvedValue': '೯೬%',
      'press.title': 'ಪತ್ರಿಕಾ ಪ್ರಕಟಣೆ',
      'press.viewAll': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'press.readMore': 'ಇನ್ನಷ್ಟು ಓದಿ',
      'press.month1': 'ಮಾರ್ಚ್ ೨೨',
      'press.title1': 'BE(A)WARE – ಆರ್ಥಿಕ ವಂಚನೆಯ ಕಾರ್ಯವಿಧಾನದ ಕೈಪಿಡಿ',
      'press.desc1': 'ರಿಸರ್ವ್ ಬ್ಯಾಂಕ್ ಇಂದು "BE(A)WARE" ಕೈಪಿಡಿಯನ್ನು ಬಿಡುಗಡೆ ಮಾಡಿದೆ, ಇದು ವಂಚಕರ ಸಾಮಾನ್ಯ ಕಾರ್ಯವಿಧಾನ ಮತ್ತು ಹಣಕಾಸು ವಹಿವಾಟುಗಳಲ್ಲಿ ತೆಗೆದುಕೊಳ್ಳಬೇಕಾದ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳ ಬಗ್ಗೆ.',
      'press.month2': 'ಫೆಬ್ರ ೨೨',
      'press.title2': 'RBI ತನ್ನ ಹೆಸರಿನಲ್ಲಿ ನಕಲಿ ವೆಬ್‌ಸೈಟ್‌ಗಳ ಬಗ್ಗೆ ಎಚ್ಚರಿಕೆ',
      'press.desc2': 'ರಿಸರ್ವ್ ಬ್ಯಾಂಕ್ ತನ್ನ ಹೆಸರಿನಲ್ಲಿ ನಕಲಿ ವೆಬ್‌ಸೈಟ್‌ಗಳ ಬಗ್ಗೆ ಜನರನ್ನು ಎಚ್ಚರಿಸಿದೆ.',
      'edu.tag': 'ಸಾರ್ವಜನಿಕ ಜಾಗೃತಿ',
      'edu.title': 'ಶಿಕ್ಷಣ ಮತ್ತು ಜಾಗೃತಿ',
      'edu.watch': 'ನೋಡಿ',
      'edu.read': 'ಓದಿ',
      'edu.card1Title': 'ಮೂಲ ಉಳಿತಾಯ ಬ್ಯಾಂಕ್ ಠೇವಣಿ ಖಾತೆ (BSBDA)',
      'edu.card1Subtitle': 'ಮೂಲ ಉಳಿತಾಯ ಬ್ಯಾಂಕ್ ಠೇವಣಿ ಖಾತೆ BSBDA',
      'edu.card2Title': 'ಅನಧಿಕೃತ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಬ್ಯಾಂಕಿಂಗ್ ವಹಿವಾಟುಗಳಲ್ಲಿ ಗ್ರಾಹಕ ಹೊಣೆಗಾರಿಕೆ',
      'edu.card2Subtitle': 'ಅನಧಿಕೃತ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಬ್ಯಾಂಕಿಂಗ್ ವಹಿವಾಟುಗಳಲ್ಲಿ ಗ್ರಾಹಕ ಹೊಣೆಗಾರಿಕೆ',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'ಆರ್ಥಿಕ ವಂಚಕರ ಕಾರ್ಯವಿಧಾನದ ಕೈಪಿಡಿ',
      'edu.card4Title': 'ಅನಧಿಕೃತ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಬ್ಯಾಂಕಿಂಗ್ ವಹಿವಾಟುಗಳಲ್ಲಿ ಗ್ರಾಹಕ ಹೊಣೆಗಾರಿಕೆ',
      'edu.card4Subtitle': 'ಮೂಲ ಉಳಿತಾಯ ಬ್ಯಾಂಕ್ ಠೇವಣಿ ಖಾತೆ BSBDA',
      'faq.tag': 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
      'faq.title': 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
      'faq.q1': 'ಈ ವೆಬ್‌ಸೈಟ್ ಮೂಲಕ ನಾನು ಯಾವ ರೀತಿಯ ದೂರುಗಳನ್ನು ಸಲ್ಲಿಸಬಹುದು?',
      'faq.a1': 'ಈ ವೆಬ್‌ಸೈಟ್ ಭಾರತೀಯ ರಿಸರ್ವ್ ಬ್ಯಾಂಕ್ ನಿಯಂತ್ರಿತ ವಾಣಿಜ್ಯ ಬ್ಯಾಂಕ್‌ಗಳು, ನಗರ ಸಹಕಾರ ಬ್ಯಾಂಕ್‌ಗಳು, ಬ್ಯಾಂಕೇತರ ಹಣಕಾಸು ಸಂಸ್ಥೆಗಳು ಮತ್ತು ಪಾವತಿ ವ್ಯವಸ್ಥೆ ಭಾಗವಹಿಸುವವರ ಸೇವಾ ಕೊರತೆ ಬಗ್ಗೆ ದೂರು ಸಲ್ಲಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
      'faq.q2': 'ನನ್ನ ದೂರಿನ ಸ್ಥಿತಿಯನ್ನು ಹೇಗೆ ಟ್ರ್ಯಾಕ್ ಮಾಡುವುದು?',
      'faq.a2': '"ದೂರು ಟ್ರ್ಯಾಕ್" ಕ್ಲಿಕ್ ಮಾಡಿ ನಿಮ್ಮ ದೂರು ಸಂಖ್ಯೆ ನಮೂದಿಸಿ ಸ್ಥಿತಿ ತಿಳಿಯಬಹುದು.',
      'faq.q3': 'ದೂರು ಪರಿಹಾರಕ್ಕೆ ಸಮಯ ಮಿತಿ ಏನು?',
      'faq.a3': 'ನಿಯಂತ್ರಿತ ಸಂಸ್ಥೆ ದೂರು ಸ್ವೀಕರಿಸಿದ ೩೦ ದಿನಗಳಲ್ಲಿ ಪರಿಹರಿಸಬೇಕು. ತೃಪ್ತಿ ಇಲ್ಲದಿದ್ದರೆ ಈ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ದೂರು ಸಲ್ಲಿಸಬಹುದು.',
      'dashboard.home': 'ಮುಖಪುಟ',
      'dashboard.fileNew': 'ಹೊಸ ದೂರು ಸಲ್ಲಿಸಿ',
      'dashboard.history': 'ದೂರು ಇತಿಹಾಸ',
      'dashboard.id': 'ಐಡಿ',
      'dashboard.against': 'ಯಾರ ವಿರುದ್ಧ',
      'dashboard.date': 'ದೂರು ದಿನಾಂಕ',
      'dashboard.status': 'ಸ್ಥಿತಿ',
      'dashboard.comments': 'ಟಿಪ್ಪಣಿಗಳು',
      'dashboard.action': 'ಕ್ರಿಯೆ',
      'dashboard.withdraw': 'ಹಿಂತೆಗೆದುಕೊಳ್ಳಿ',
      'dashboard.appeal': 'ಮೇಲ್ಮನವಿ',
      'dashboard.act': 'ಕ್ರಿಯೆ',
      'file.title': 'ದೂರು ಸಲ್ಲಿಸಿ',
      'file.next': 'ಮುಂದೆ',
      'file.previous': 'ಹಿಂದೆ',
      'file.submit': 'ಸಲ್ಲಿಸಿ',
      'track.title': 'ನಿಮ್ಮ ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'track.placeholder': 'ದೂರು ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      'track.search': 'ಹುಡುಕಿ',
      'common.search': 'ಹುಡುಕಿ',
      'common.cancel': 'ರದ್ದು',
      'common.close': 'ಮುಚ್ಚಿ',
      'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    },

    ml: {
      'header.brandHindi': 'പരാതി നിർവഹണ സംവിധാനം',
      'header.brandEnglish': 'പരാതി നിർവഹണ സംവിധാനം',
      'header.home': 'ഹോം',
      'header.aboutUs': 'ഞങ്ങളെ കുറിച്ച്',
      'header.publicAwareness': 'പൊതു അവബോധം',
      'header.contact': 'ബന്ധപ്പെടുക',
      'header.physicalFiling': 'ഭൗതിക പരാതി',
      'header.lastSignedIn': 'അവസാന ലോഗിൻ',
      'hero.title': 'RBI-ക്ക് നിങ്ങളുടെ പരാതി',
      'hero.titleHighlight': 'ആത്മവിശ്വാസത്തോടെ',
      'hero.subtitle': 'പരാതി പരിഹാരത്തിനുള്ള നിങ്ങളുടെ വിശ്വസ്ത പ്ലാറ്റ്‌ഫോം - നിയന്ത്രിത സ്ഥാപനങ്ങൾക്കെതിരെ എളുപ്പത്തിൽ പരാതി ഫയൽ ചെയ്ത് ട്രാക്ക് ചെയ്യുക.',
      'hero.fileComplaint': 'പരാതി രജിസ്റ്റർ ചെയ്യുക',
      'hero.alreadyFiled': 'ഇതിനകം പരാതി നൽകിയോ?',
      'hero.trackOrWithdraw': 'പരാതി ട്രാക്ക്/പിൻവലിക്കുക',
      'hero.fileAppeal': 'അപ്പീൽ ഫയൽ ചെയ്യുക',
      'hero.shareFeedback': 'ഫീഡ്‌ബാക്ക് നൽകുക',
      'hero.emailSimulation': 'ഇമെയിൽ സിമുലേഷൻ',
      'hero.needHelp': 'സഹായം വേണോ?',
      'ct.findInstitution': 'നിങ്ങളുടെ സാമ്പത്തിക സ്ഥാപനം കണ്ടെത്തുക',
      'ct.title': 'നിങ്ങൾക്ക് ഇവയെക്കുറിച്ച് പരാതി നൽകാം',
      'ct.searchPlaceholder': 'സ്ഥാപനം തിരയുക',
      'ct.searchHint': 'തിരയാൻ ആഗ്രഹിക്കുന്ന ബാങ്കിന്റെ അല്ലെങ്കിൽ സാമ്പത്തിക സ്ഥാപനത്തിന്റെ പേര് നൽകുക',
      'ct.allBanks': 'എല്ലാ വാണിജ്യ ബാങ്കുകളും',
      'ct.nbfc': 'ബാങ്കിതര സാമ്പത്തിക സ്ഥാപനങ്ങൾ',
      'ct.creditInfo': 'ക്രെഡിറ്റ് വിവര സ്ഥാപനങ്ങൾ',
      'ct.paymentSystem': 'പേയ്‌മെന്റ് സിസ്റ്റം പങ്കാളികൾ',
      'whatwedo.tag': 'ഞങ്ങൾ എന്ത് ചെയ്യുന്നു',
      'whatwedo.title': 'ഇന്ത്യൻ പൗരന്മാർക്കായി RBI പരാതി പരിഹാര പ്രക്രിയ ലളിതമാക്കുന്നു.',
      'whatwedo.desc': 'RBI ഇന്ത്യൻ പൗരന്മാർക്കായി പരാതി പരിഹാര പ്രക്രിയ ലളിതവും വേഗത്തിലുമാക്കുന്നു.',
      'whatwedo.howToFile': 'പരാതി എങ്ങനെ ഫയൽ ചെയ്യാം',
      'whatwedo.whatWeCanHelp': 'ഞങ്ങൾക്ക് എന്ത് സഹായിക്കാനാകും',
      'stats.tag': 'സ്ഥിതിവിവരക്കണക്കുകൾ',
      'stats.received': 'പരാതികൾ ലഭിച്ചു',
      'stats.handled': 'പരാതികൾ കൈകാര്യം ചെയ്തു',
      'stats.resolved': 'പരാതികൾ പരിഹരിച്ചു',
      'stats.receivedValue': '9,50,000',
      'stats.handledValue': '8,75,000',
      'stats.resolvedValue': '96%',
      'press.title': 'പത്രക്കുറിപ്പ്',
      'press.viewAll': 'എല്ലാം കാണുക',
      'press.readMore': 'കൂടുതൽ വായിക്കുക',
      'press.month1': 'മാർ 22',
      'press.title1': 'BE(A)WARE – സാമ്പത്തിക തട്ടിപ്പുകളുടെ പ്രവർത്തനരീതി കൈപ്പുസ്തകം',
      'press.desc1': 'റിസർവ് ബാങ്ക് ഇന്ന് "BE(A)WARE" കൈപ്പുസ്തകം പുറത്തിറക്കി, ഇത് തട്ടിപ്പുകാരുടെ സാധാരണ പ്രവർത്തനരീതിയും സാമ്പത്തിക ഇടപാടുകൾ നടത്തുമ്പോൾ എടുക്കേണ്ട മുൻകരുതലുകളും വിവരിക്കുന്നു.',
      'press.month2': 'ഫെബ്ര 22',
      'press.title2': 'RBI അതിന്റെ പേരിലുള്ള വ്യാജ വെബ്‌സൈറ്റുകളെ കുറിച്ച് മുന്നറിയിപ്പ്',
      'press.desc2': 'റിസർവ് ബാങ്ക് അതിന്റെ പേരിലുള്ള വ്യാജ വെബ്‌സൈറ്റുകളെ കുറിച്ച് ജനങ്ങളെ ജാഗ്രതപ്പെടുത്തി.',
      'edu.tag': 'പൊതു അവബോധം',
      'edu.title': 'വിദ്യാഭ്യാസവും അവബോധവും',
      'edu.watch': 'കാണുക',
      'edu.read': 'വായിക്കുക',
      'edu.card1Title': 'അടിസ്ഥാന സേവിംഗ്സ് ബാങ്ക് ഡെപ്പോസിറ്റ് അക്കൗണ്ട് (BSBDA)',
      'edu.card1Subtitle': 'അടിസ്ഥാന സേവിംഗ്സ് ബാങ്ക് ഡെപ്പോസിറ്റ് അക്കൗണ്ട് BSBDA',
      'edu.card2Title': 'അനധികൃത ഇലക്ട്രോണിക് ബാങ്കിംഗ് ഇടപാടുകളിലെ ഉപഭോക്തൃ ബാധ്യത',
      'edu.card2Subtitle': 'അനധികൃത ഇലക്ട്രോണിക് ബാങ്കിംഗ് ഇടപാടുകളിലെ ഉപഭോക്തൃ ബാധ്യത',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'സാമ്പത്തിക തട്ടിപ്പുകാരുടെ പ്രവർത്തനരീതി കൈപ്പുസ്തകം',
      'edu.card4Title': 'അനധികൃത ഇലക്ട്രോണിക് ബാങ്കിംഗ് ഇടപാടുകളിലെ ഉപഭോക്തൃ ബാധ്യത',
      'edu.card4Subtitle': 'അടിസ്ഥാന സേവിംഗ്സ് ബാങ്ക് ഡെപ്പോസിറ്റ് അക്കൗണ്ട് BSBDA',
      'faq.tag': 'പതിവ് ചോദ്യങ്ങൾ',
      'faq.title': 'പതിവ് ചോദ്യങ്ങൾ',
      'faq.q1': 'ഈ വെബ്‌സൈറ്റ് വഴി ഏത് തരം പരാതികൾ നൽകാം?',
      'faq.a1': 'ഈ വെബ്‌സൈറ്റ് ഇന്ത്യൻ റിസർവ് ബാങ്ക് നിയന്ത്രിത വാണിജ്യ ബാങ്കുകൾ, നഗര സഹകരണ ബാങ്കുകൾ, ബാങ്കിതര സാമ്പത്തിക സ്ഥാപനങ്ങൾ, പേയ്‌മെന്റ് സിസ്റ്റം പങ്കാളികളുടെ സേവന കുറവ് സംബന്ധിച്ച പരാതികൾ ഫയൽ ചെയ്യാൻ സഹായിക്കുന്നു.',
      'faq.q2': 'എന്റെ പരാതിയുടെ നില എങ്ങനെ ട്രാക്ക് ചെയ്യാം?',
      'faq.a2': '"പരാതി ട്രാക്ക്" ക്ലിക്ക് ചെയ്ത് നിങ്ങളുടെ പരാതി റഫറൻസ് നമ്പർ നൽകി നില അറിയാം.',
      'faq.q3': 'പരാതി പരിഹരിക്കാനുള്ള സമയപരിധി എന്താണ്?',
      'faq.a3': 'നിയന്ത്രിത സ്ഥാപനം പരാതി ലഭിച്ച് 30 ദിവസത്തിനകം പരിഹരിക്കണം. തൃപ്തികരമല്ലെങ്കിൽ ഈ പോർട്ടലിൽ പരാതി നൽകാം.',
      'dashboard.home': 'ഹോം',
      'dashboard.fileNew': 'പുതിയ പരാതി ഫയൽ ചെയ്യുക',
      'dashboard.history': 'പരാതി ചരിത്രം',
      'dashboard.id': 'ഐഡി',
      'dashboard.against': 'ആർക്കെതിരെ',
      'dashboard.date': 'പരാതി തീയതി',
      'dashboard.status': 'സ്ഥിതി',
      'dashboard.comments': 'അഭിപ്രായങ്ങൾ',
      'dashboard.action': 'നടപടി',
      'dashboard.withdraw': 'പിൻവലിക്കുക',
      'dashboard.appeal': 'അപ്പീൽ',
      'dashboard.act': 'നടപടി',
      'file.title': 'പരാതി രജിസ്റ്റർ ചെയ്യുക',
      'file.next': 'അടുത്തത്',
      'file.previous': 'മുമ്പത്തേത്',
      'file.submit': 'സമർപ്പിക്കുക',
      'track.title': 'നിങ്ങളുടെ പരാതി ട്രാക്ക് ചെയ്യുക',
      'track.placeholder': 'പരാതി നമ്പർ നൽകുക',
      'track.search': 'തിരയുക',
      'common.search': 'തിരയുക',
      'common.cancel': 'റദ്ദാക്കുക',
      'common.close': 'അടയ്ക്കുക',
      'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    },

    pa: {
      'header.brandHindi': 'ਸ਼ਿਕਾਇਤ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ',
      'header.brandEnglish': 'ਸ਼ਿਕਾਇਤ ਪ੍ਰਬੰਧਨ ਪ੍ਰਣਾਲੀ',
      'header.home': 'ਹੋਮ',
      'header.aboutUs': 'ਸਾਡੇ ਬਾਰੇ',
      'header.publicAwareness': 'ਜਨ ਜਾਗਰੂਕਤਾ',
      'header.contact': 'ਸੰਪਰਕ',
      'header.physicalFiling': 'ਭੌਤਿਕ ਸ਼ਿਕਾਇਤ',
      'header.lastSignedIn': 'ਆਖਰੀ ਲੌਗਇਨ',
      'hero.title': 'RBI ਨੂੰ ਤੁਹਾਡੀ ਸ਼ਿਕਾਇਤ',
      'hero.titleHighlight': 'ਭਰੋਸੇ ਨਾਲ',
      'hero.subtitle': 'ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ ਲਈ ਤੁਹਾਡਾ ਭਰੋਸੇਮੰਦ ਪਲੇਟਫਾਰਮ - ਨਿਯਮਿਤ ਸੰਸਥਾਵਾਂ ਵਿਰੁੱਧ ਅਸਾਨੀ ਨਾਲ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ ਅਤੇ ਟ੍ਰੈਕ ਕਰੋ।',
      'hero.fileComplaint': 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
      'hero.alreadyFiled': 'ਪਹਿਲਾਂ ਹੀ ਸ਼ਿਕਾਇਤ ਕੀਤੀ ਹੈ?',
      'hero.trackOrWithdraw': 'ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ/ਵਾਪਸ ਲਓ',
      'hero.fileAppeal': 'ਅਪੀਲ ਦਾਇਰ ਕਰੋ',
      'hero.shareFeedback': 'ਫੀਡਬੈਕ ਦਿਓ',
      'hero.emailSimulation': 'ਈਮੇਲ ਸਿਮੂਲੇਸ਼ਨ',
      'hero.needHelp': 'ਮਦਦ ਚਾਹੀਦੀ?',
      'ct.findInstitution': 'ਆਪਣੀ ਵਿੱਤੀ ਸੰਸਥਾ ਲੱਭੋ',
      'ct.title': 'ਤੁਸੀਂ ਇਨ੍ਹਾਂ ਬਾਰੇ ਸ਼ਿਕਾਇਤ ਕਰ ਸਕਦੇ ਹੋ',
      'ct.searchPlaceholder': 'ਸੰਸਥਾ ਖੋਜੋ',
      'ct.searchHint': 'ਜਿਸ ਬੈਂਕ ਜਾਂ ਵਿੱਤੀ ਸੰਸਥਾ ਨੂੰ ਖੋਜਣਾ ਚਾਹੁੰਦੇ ਹੋ ਉਸ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
      'ct.allBanks': 'ਸਾਰੇ ਵਪਾਰਕ ਬੈਂਕ',
      'ct.nbfc': 'ਗੈਰ-ਬੈਂਕਿੰਗ ਵਿੱਤੀ ਕੰਪਨੀਆਂ',
      'ct.creditInfo': 'ਕ੍ਰੈਡਿਟ ਜਾਣਕਾਰੀ ਕੰਪਨੀਆਂ',
      'ct.paymentSystem': 'ਭੁਗਤਾਨ ਪ੍ਰਣਾਲੀ ਭਾਗੀਦਾਰ',
      'whatwedo.tag': 'ਅਸੀਂ ਕੀ ਕਰਦੇ ਹਾਂ',
      'whatwedo.title': 'RBI ਭਾਰਤੀ ਨਾਗਰਿਕਾਂ ਲਈ ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ ਪ੍ਰਕਿਰਿਆ ਨੂੰ ਸਰਲ ਬਣਾਉਂਦਾ ਹੈ।',
      'whatwedo.desc': 'RBI ਭਾਰਤੀ ਨਾਗਰਿਕਾਂ ਲਈ ਸ਼ਿਕਾਇਤ ਨਿਵਾਰਨ ਪ੍ਰਕਿਰਿਆ ਨੂੰ ਸਰਲ ਅਤੇ ਤੇਜ਼ ਬਣਾਉਂਦਾ ਹੈ।',
      'whatwedo.howToFile': 'ਸ਼ਿਕਾਇਤ ਕਿਵੇਂ ਦਰਜ ਕਰੀਏ',
      'whatwedo.whatWeCanHelp': 'ਅਸੀਂ ਕੀ ਮਦਦ ਕਰ ਸਕਦੇ ਹਾਂ',
      'stats.tag': 'ਅੰਕੜੇ',
      'stats.received': 'ਸ਼ਿਕਾਇਤਾਂ ਪ੍ਰਾਪਤ',
      'stats.handled': 'ਸ਼ਿਕਾਇਤਾਂ ਸੰਭਾਲੀਆਂ',
      'stats.resolved': 'ਸ਼ਿਕਾਇਤਾਂ ਹੱਲ',
      'stats.receivedValue': '੯,੫੦,੦੦੦',
      'stats.handledValue': '੮,੭੫,੦੦੦',
      'stats.resolvedValue': '੯੬%',
      'press.title': 'ਪ੍ਰੈਸ ਰਿਲੀਜ਼',
      'press.viewAll': 'ਸਭ ਦੇਖੋ',
      'press.readMore': 'ਹੋਰ ਪੜ੍ਹੋ',
      'press.month1': 'ਮਾਰਚ ੨੨',
      'press.title1': 'BE(A)WARE – ਵਿੱਤੀ ਧੋਖਾਧੜੀ ਦੀ ਕਾਰਜ-ਪ੍ਰਣਾਲੀ \'ਤੇ ਪੁਸਤਿਕਾ',
      'press.desc1': 'ਰਿਜ਼ਰਵ ਬੈਂਕ ਨੇ ਅੱਜ "BE(A)WARE" ਪੁਸਤਿਕਾ ਜਾਰੀ ਕੀਤੀ ਹੈ ਜੋ ਧੋਖੇਬਾਜ਼ਾਂ ਦੀ ਆਮ ਕਾਰਜ-ਪ੍ਰਣਾਲੀ ਅਤੇ ਵਿੱਤੀ ਲੈਣ-ਦੇਣ ਸਮੇਂ ਸਾਵਧਾਨੀਆਂ ਬਾਰੇ ਹੈ।',
      'press.month2': 'ਫ਼ਰ ੨੨',
      'press.title2': 'RBI ਨੇ ਆਪਣੇ ਨਾਮ \'ਤੇ ਨਕਲੀ ਵੈੱਬਸਾਈਟਾਂ ਬਾਰੇ ਚੇਤਾਵਨੀ ਦਿੱਤੀ',
      'press.desc2': 'ਰਿਜ਼ਰਵ ਬੈਂਕ ਨੇ ਲੋਕਾਂ ਨੂੰ ਆਪਣੇ ਨਾਮ \'ਤੇ ਨਕਲੀ ਵੈੱਬਸਾਈਟਾਂ ਬਾਰੇ ਸੁਚੇਤ ਕੀਤਾ ਹੈ।',
      'edu.tag': 'ਜਨ ਜਾਗਰੂਕਤਾ',
      'edu.title': 'ਸਿੱਖਿਆ ਅਤੇ ਜਾਗਰੂਕਤਾ',
      'edu.watch': 'ਦੇਖੋ',
      'edu.read': 'ਪੜ੍ਹੋ',
      'edu.card1Title': 'ਬੇਸਿਕ ਸੇਵਿੰਗਜ਼ ਬੈਂਕ ਡਿਪਾਜ਼ਿਟ ਖਾਤਾ (BSBDA)',
      'edu.card1Subtitle': 'ਬੇਸਿਕ ਸੇਵਿੰਗਜ਼ ਬੈਂਕ ਡਿਪਾਜ਼ਿਟ ਖਾਤਾ BSBDA',
      'edu.card2Title': 'ਅਣਅਧਿਕਾਰਤ ਇਲੈਕਟ੍ਰਾਨਿਕ ਬੈਂਕਿੰਗ ਲੈਣ-ਦੇਣ ਵਿੱਚ ਗਾਹਕ ਜ਼ਿੰਮੇਵਾਰੀ',
      'edu.card2Subtitle': 'ਅਣਅਧਿਕਾਰਤ ਇਲੈਕਟ੍ਰਾਨਿਕ ਬੈਂਕਿੰਗ ਲੈਣ-ਦੇਣ ਵਿੱਚ ਗਾਹਕ ਜ਼ਿੰਮੇਵਾਰੀ',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'ਵਿੱਤੀ ਧੋਖੇਬਾਜ਼ਾਂ ਦੀ ਕਾਰਜ-ਪ੍ਰਣਾਲੀ \'ਤੇ ਪੁਸਤਿਕਾ',
      'edu.card4Title': 'ਅਣਅਧਿਕਾਰਤ ਇਲੈਕਟ੍ਰਾਨਿਕ ਬੈਂਕਿੰਗ ਲੈਣ-ਦੇਣ ਵਿੱਚ ਗਾਹਕ ਜ਼ਿੰਮੇਵਾਰੀ',
      'edu.card4Subtitle': 'ਬੇਸਿਕ ਸੇਵਿੰਗਜ਼ ਬੈਂਕ ਡਿਪਾਜ਼ਿਟ ਖਾਤਾ BSBDA',
      'faq.tag': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
      'faq.title': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
      'faq.q1': 'ਇਸ ਵੈੱਬਸਾਈਟ ਰਾਹੀਂ ਮੈਂ ਕਿਸ ਤਰ੍ਹਾਂ ਦੀਆਂ ਸ਼ਿਕਾਇਤਾਂ ਦਰਜ ਕਰ ਸਕਦਾ ਹਾਂ?',
      'faq.a1': 'ਇਹ ਵੈੱਬਸਾਈਟ ਭਾਰਤੀ ਰਿਜ਼ਰਵ ਬੈਂਕ ਦੁਆਰਾ ਨਿਯਮਿਤ ਵਪਾਰਕ ਬੈਂਕਾਂ, ਸ਼ਹਿਰੀ ਸਹਿਕਾਰੀ ਬੈਂਕਾਂ, ਗੈਰ-ਬੈਂਕਿੰਗ ਵਿੱਤੀ ਕੰਪਨੀਆਂ ਅਤੇ ਭੁਗਤਾਨ ਪ੍ਰਣਾਲੀ ਭਾਗੀਦਾਰਾਂ ਦੀ ਸੇਵਾ ਕਮੀ ਬਾਰੇ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ।',
      'faq.q2': 'ਮੈਂ ਆਪਣੀ ਸ਼ਿਕਾਇਤ ਦੀ ਸਥਿਤੀ ਕਿਵੇਂ ਟ੍ਰੈਕ ਕਰਾਂ?',
      'faq.a2': '"ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ" \'ਤੇ ਕਲਿੱਕ ਕਰਕੇ ਆਪਣਾ ਸ਼ਿਕਾਇਤ ਨੰਬਰ ਦਰਜ ਕਰੋ ਤੇ ਸਥਿਤੀ ਜਾਣੋ।',
      'faq.q3': 'ਸ਼ਿਕਾਇਤ ਦੇ ਨਿਵਾਰਨ ਲਈ ਸਮਾਂ ਸੀਮਾ ਕੀ ਹੈ?',
      'faq.a3': 'ਨਿਯਮਿਤ ਸੰਸਥਾ ਨੂੰ ਸ਼ਿਕਾਇਤ ਮਿਲਣ ਤੋਂ 30 ਦਿਨਾਂ ਵਿੱਚ ਹੱਲ ਕਰਨਾ ਜ਼ਰੂਰੀ ਹੈ। ਸੰਤੁਸ਼ਟ ਨਾ ਹੋਵੋ ਤਾਂ ਇਸ ਪੋਰਟਲ \'ਤੇ ਸ਼ਿਕਾਇਤ ਕਰੋ।',
      'dashboard.home': 'ਹੋਮ',
      'dashboard.fileNew': 'ਨਵੀਂ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
      'dashboard.history': 'ਸ਼ਿਕਾਇਤ ਇਤਿਹਾਸ',
      'dashboard.id': 'ਆਈਡੀ',
      'dashboard.against': 'ਕਿਸ ਵਿਰੁੱਧ',
      'dashboard.date': 'ਸ਼ਿਕਾਇਤ ਤਾਰੀਖ',
      'dashboard.status': 'ਸਥਿਤੀ',
      'dashboard.comments': 'ਟਿੱਪਣੀਆਂ',
      'dashboard.action': 'ਕਾਰਵਾਈ',
      'dashboard.withdraw': 'ਵਾਪਸ ਲਓ',
      'dashboard.appeal': 'ਅਪੀਲ',
      'dashboard.act': 'ਕਾਰਵਾਈ',
      'file.title': 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
      'file.next': 'ਅਗਲਾ',
      'file.previous': 'ਪਿਛਲਾ',
      'file.submit': 'ਜਮ੍ਹਾਂ ਕਰੋ',
      'track.title': 'ਆਪਣੀ ਸ਼ਿਕਾਇਤ ਟ੍ਰੈਕ ਕਰੋ',
      'track.placeholder': 'ਸ਼ਿਕਾਇਤ ਨੰਬਰ ਦਰਜ ਕਰੋ',
      'track.search': 'ਖੋਜੋ',
      'common.search': 'ਖੋਜੋ',
      'common.cancel': 'ਰੱਦ',
      'common.close': 'ਬੰਦ',
      'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    },

    or: {
      'header.brandHindi': 'ଅଭିଯୋଗ ପରିଚାଳନା ପ୍ରଣାଳୀ',
      'header.brandEnglish': 'ଅଭିଯୋଗ ପରିଚାଳନା ପ୍ରଣାଳୀ',
      'header.home': 'ହୋମ',
      'header.aboutUs': 'ଆମ ବିଷୟରେ',
      'header.publicAwareness': 'ଜନ ସଚେତନତା',
      'header.contact': 'ଯୋଗାଯୋଗ',
      'header.physicalFiling': 'ଭୌତିକ ଅଭିଯୋଗ',
      'header.lastSignedIn': 'ଶେଷ ଲଗଇନ',
      'hero.title': 'RBI କୁ ଆପଣଙ୍କ ଅଭିଯୋଗ',
      'hero.titleHighlight': 'ବିଶ୍ୱାସ ସହ',
      'hero.subtitle': 'ଅଭିଯୋଗ ସମାଧାନ ପାଇଁ ଆପଣଙ୍କ ବିଶ୍ୱସ୍ତ ପ୍ଲାଟଫର୍ମ - ନିୟନ୍ତ୍ରିତ ସଂସ୍ଥା ବିରୁଦ୍ଧରେ ସହଜରେ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ ଏବଂ ଟ୍ରାକ କରନ୍ତୁ।',
      'hero.fileComplaint': 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
      'hero.alreadyFiled': 'ପୂର୍ବରୁ ଅଭିଯୋଗ କରିଛନ୍ତି?',
      'hero.trackOrWithdraw': 'ଅଭିଯୋଗ ଟ୍ରାକ/ପ୍ରତ୍ୟାହାର',
      'hero.fileAppeal': 'ଅପିଲ ଦାଖଲ',
      'hero.shareFeedback': 'ମତାମତ ଦିଅନ୍ତୁ',
      'hero.emailSimulation': 'ଇମେଲ ସିମୁଲେସନ',
      'hero.needHelp': 'ସାହାଯ୍ୟ ଦରକାର?',
      'ct.findInstitution': 'ଆପଣଙ୍କ ଆର୍ଥିକ ସଂସ୍ଥା ଖୋଜନ୍ତୁ',
      'ct.title': 'ଆପଣ ଏହି ସମ୍ପର୍କରେ ଅଭିଯୋଗ କରିପାରିବେ',
      'ct.searchPlaceholder': 'ସଂସ୍ଥା ଖୋଜନ୍ତୁ',
      'ct.searchHint': 'ଖୋଜିବାକୁ ଚାହୁଁଥିବା ବ୍ୟାଙ୍କ ବା ଆର୍ଥିକ ସଂସ୍ଥାର ନାମ ଲେଖନ୍ତୁ',
      'ct.allBanks': 'ସମସ୍ତ ବାଣିଜ୍ୟିକ ବ୍ୟାଙ୍କ',
      'ct.nbfc': 'ଅଣ-ବ୍ୟାଙ୍କିଂ ଆର୍ଥିକ ସଂସ୍ଥା',
      'ct.creditInfo': 'କ୍ରେଡିଟ ସୂଚନା ସଂସ୍ଥା',
      'ct.paymentSystem': 'ଭୁଗତାନ ପ୍ରଣାଳୀ ଅଂଶଗ୍ରହଣକାରୀ',
      'whatwedo.tag': 'ଆମେ କ\'ଣ କରୁ',
      'whatwedo.title': 'RBI ଭାରତୀୟ ନାଗରିକଙ୍କ ପାଇଁ ଅଭିଯୋଗ ସମାଧାନ ପ୍ରକ୍ରିୟା ସରଳ କରେ।',
      'whatwedo.desc': 'RBI ଭାରତୀୟ ନାଗରିକଙ୍କ ପାଇଁ ଅଭିଯୋଗ ସମାଧାନ ପ୍ରକ୍ରିୟା ସରଳ ଏବଂ ଦ୍ରୁତ କରେ।',
      'whatwedo.howToFile': 'ଅଭିଯୋଗ କିପରି ଦାଖଲ କରିବେ',
      'whatwedo.whatWeCanHelp': 'ଆମେ କ\'ଣ ସାହାଯ୍ୟ କରିପାରିବା',
      'stats.tag': 'ପରିସଂଖ୍ୟାନ',
      'stats.received': 'ଅଭିଯୋଗ ପ୍ରାପ୍ତ',
      'stats.handled': 'ଅଭିଯୋଗ ପରିଚାଳିତ',
      'stats.resolved': 'ଅଭିଯୋଗ ସମାଧାନ',
      'stats.receivedValue': '୯,୫୦,୦୦୦',
      'stats.handledValue': '୮,୭୫,୦୦୦',
      'stats.resolvedValue': '୯୬%',
      'press.title': 'ସାମ୍ବାଦିକ ବିଜ୍ଞପ୍ତି',
      'press.viewAll': 'ସବୁ ଦେଖନ୍ତୁ',
      'press.readMore': 'ଆହୁରି ପଢ଼ନ୍ତୁ',
      'press.month1': 'ମାର୍ଚ୍ ୨୨',
      'press.title1': 'BE(A)WARE – ଆର୍ଥିକ ଜାଲିଆତିର କାର୍ଯ୍ୟପଦ୍ଧତି ଉପରେ ପୁସ୍ତିକା',
      'press.desc1': 'ରିଜର୍ଭ ବ୍ୟାଙ୍କ ଆଜି "BE(A)WARE" ପୁସ୍ତିକା ପ୍ରକାଶ କରିଛି ଯାହା ଜାଲିଆତମାନଙ୍କ ସାଧାରଣ କାର୍ଯ୍ୟପଦ୍ଧତି ଏବଂ ଆର୍ଥିକ ଲେନଦେନ ସମୟରେ ସାବଧାନତା ବିଷୟରେ।',
      'press.month2': 'ଫେବ୍ରୁ ୨୨',
      'press.title2': 'RBI ନିଜ ନାମରେ ନକଲି ୱେବସାଇଟ ବିଷୟରେ ସତର୍କତା',
      'press.desc2': 'ରିଜର୍ଭ ବ୍ୟାଙ୍କ ଜନସାଧାରଣଙ୍କୁ ନିଜ ନାಮରେ ନକଲି ୱେବସାଇଟ ବିଷୟରେ ସତର୍କ କରିଛି।',
      'edu.tag': 'ଜନ ସଚେତନତା',
      'edu.title': 'ଶିକ୍ଷା ଏବଂ ସଚେତନତା',
      'edu.watch': 'ଦେଖନ୍ତୁ',
      'edu.read': 'ପଢ଼ନ୍ତୁ',
      'edu.card1Title': 'ମୌଳିକ ସଞ୍ଚୟ ବ୍ୟାଙ୍କ ଜମା ଖାତା (BSBDA)',
      'edu.card1Subtitle': 'ମୌଳିକ ସଞ୍ଚୟ ବ୍ୟାଙ୍କ ଜମା ଖାତା BSBDA',
      'edu.card2Title': 'ଅନଧିକୃତ ଇଲେକ୍ଟ୍ରନିକ ବ୍ୟାଙ୍କିଂ ଲେନଦେନରେ ଗ୍ରାହକ ଦାୟିତ୍ୱ',
      'edu.card2Subtitle': 'ଅନଧିକୃତ ଇଲେକ୍ଟ୍ରନିକ ବ୍ୟାଙ୍କିଂ ଲେନଦେନରେ ଗ୍ରାହକ ଦାୟିତ୍ୱ',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'ଆର୍ଥିକ ଜାଲିଆତମାନଙ୍କ କାର୍ଯ୍ୟପଦ୍ଧତି ଉପରେ ପୁସ୍ତିକା',
      'edu.card4Title': 'ଅନଧିକୃତ ଇଲେକ୍ଟ୍ରନିକ ବ୍ୟାଙ୍କିଂ ଲେନଦେନରେ ଗ୍ରାହକ ଦାୟିତ୍ୱ',
      'edu.card4Subtitle': 'ମୌଳିକ ସଞ୍ଚୟ ବ୍ୟାଙ୍କ ଜମା ଖାତା BSBDA',
      'faq.tag': 'ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ',
      'faq.title': 'ବାରମ୍ବାର ପଚରାଯାଉଥିବା ପ୍ରଶ୍ନ',
      'faq.q1': 'ଏହି ୱେବସାଇଟ ମାଧ୍ୟମରେ ମୁଁ କେଉଁ ପ୍ରକାର ଅଭିଯୋଗ ଦାଖଲ କରିପାରିବି?',
      'faq.a1': 'ଏହି ୱେବସାଇଟ ଭାରତୀୟ ରିଜର୍ଭ ବ୍ୟାଙ୍କ ଦ୍ୱାରା ନିୟନ୍ତ୍ରିତ ବାଣିଜ୍ୟିକ ବ୍ୟାଙ୍କ, ସହରାଞ୍ଚଳ ସମବାୟ ବ୍ୟାଙ୍କ, ଅଣ-ବ୍ୟାଙ୍କିଂ ଆର୍ଥିକ ସଂସ୍ଥା ଏବଂ ଭୁଗତାନ ପ୍ରଣାଳୀ ଅଂଶଗ୍ରହଣକାରୀଙ୍କ ସେବା ଅଭାବ ସମ୍ପର୍କୀୟ ଅଭିଯୋଗ ଦାଖଲ କରିବାରେ ସାହାଯ୍ୟ କରେ।',
      'faq.q2': 'ମୁଁ ମୋ ଅଭିଯୋଗର ସ୍ଥିତି କିପରି ଟ୍ରାକ କରିବି?',
      'faq.a2': '"ଅଭିଯୋଗ ଟ୍ରାକ" କ୍ଲିକ କରି ଆପଣଙ୍କ ଅଭିଯୋଗ ନମ୍ବର ଦେଇ ସ୍ଥିତି ଜାଣିପାରିବେ।',
      'faq.q3': 'ଅଭିଯୋଗ ସମାଧାନ ପାଇଁ ସମୟ ସୀମା କ\'ଣ?',
      'faq.a3': 'ନିୟନ୍ତ୍ରିତ ସଂସ୍ଥାକୁ ଅଭିଯୋଗ ପାଇବାର ୩୦ ଦିନ ମଧ୍ୟରେ ସମାଧାନ କରିବାକୁ ହେବ। ସନ୍ତୁଷ୍ଟ ନହେଲେ ଏହି ପୋର୍ଟାଲରେ ଅଭିଯୋଗ କରିପାରିବେ।',
      'dashboard.home': 'ହୋମ',
      'dashboard.fileNew': 'ନୂଆ ଅଭିଯୋଗ ଦାଖଲ',
      'dashboard.history': 'ଅଭିଯୋଗ ଇତିହାସ',
      'dashboard.id': 'ଆଇଡି',
      'dashboard.against': 'କାହା ବିରୁଦ୍ଧରେ',
      'dashboard.date': 'ଅଭିଯୋଗ ତାରିଖ',
      'dashboard.status': 'ସ୍ଥିତି',
      'dashboard.comments': 'ମନ୍ତବ୍ୟ',
      'dashboard.action': 'କାର୍ଯ୍ୟ',
      'dashboard.withdraw': 'ପ୍ରତ୍ୟାହାର',
      'dashboard.appeal': 'ଅପିଲ',
      'dashboard.act': 'କାର୍ଯ୍ୟ',
      'file.title': 'ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
      'file.next': 'ପରବର୍ତ୍ତୀ',
      'file.previous': 'ପୂର୍ବବର୍ତ୍ତୀ',
      'file.submit': 'ଦାଖଲ କରନ୍ତୁ',
      'track.title': 'ଆପଣଙ୍କ ଅଭିଯୋଗ ଟ୍ରାକ କରନ୍ତୁ',
      'track.placeholder': 'ଅଭିଯୋଗ ନମ୍ବର ଲେଖନ୍ତୁ',
      'track.search': 'ଖୋଜନ୍ତୁ',
      'common.search': 'ଖୋଜନ୍ତୁ',
      'common.cancel': 'ବାତିଲ',
      'common.close': 'ବନ୍ଦ',
      'common.loading': 'ଲୋଡ ହେଉଛି...',
    },

    as: {
      'header.brandHindi': 'অভিযোগ ব্যৱস্থাপনা প্ৰণালী',
      'header.brandEnglish': 'অভিযোগ ব্যৱস্থাপনা প্ৰণালী',
      'header.home': 'হোম',
      'header.aboutUs': 'আমাৰ বিষয়ে',
      'header.publicAwareness': 'জন সচেতনতা',
      'header.contact': 'যোগাযোগ',
      'header.physicalFiling': 'ভৌতিক অভিযোগ',
      'header.lastSignedIn': 'শেষ লগইন',
      'hero.title': 'RBI লৈ আপোনাৰ অভিযোগ',
      'hero.titleHighlight': 'আত্মবিশ্বাসেৰে',
      'hero.subtitle': 'অভিযোগ সমাধানৰ বাবে আপোনাৰ বিশ্বাসযোগ্য প্লেটফৰ্ম - নিয়ন্ত্ৰিত সংস্থাৰ বিৰুদ্ধে সহজে অভিযোগ দাখিল আৰু ট্ৰেক কৰক।',
      'hero.fileComplaint': 'অভিযোগ দাখিল কৰক',
      'hero.alreadyFiled': 'ইতিমধ্যে অভিযোগ কৰিছে?',
      'hero.trackOrWithdraw': 'অভিযোগ ট্ৰেক/প্ৰত্যাহাৰ',
      'hero.fileAppeal': 'আপীল দাখিল কৰক',
      'hero.shareFeedback': 'মতামত দিয়ক',
      'hero.emailSimulation': 'ইমেইল ছিমুলেচন',
      'hero.needHelp': 'সহায় লাগে?',
      'ct.findInstitution': 'আপোনাৰ বিত্তীয় সংস্থা বিচাৰক',
      'ct.title': 'আপুনি এইবোৰৰ বিষয়ে অভিযোগ কৰিব পাৰে',
      'ct.searchPlaceholder': 'সংস্থা বিচাৰক',
      'ct.searchHint': 'বিচাৰিব বিচৰা বেংক বা বিত্তীয় সংস্থাৰ নাম লিখক',
      'ct.allBanks': 'সকলো বাণিজ্যিক বেংক',
      'ct.nbfc': 'অ-বেংকিং বিত্তীয় সংস্থা',
      'ct.creditInfo': 'ক্ৰেডিট তথ্য সংস্থা',
      'ct.paymentSystem': 'পেমেণ্ট ছিষ্টেম অংশগ্ৰহণকাৰী',
      'whatwedo.tag': 'আমি কি কৰো',
      'whatwedo.title': 'RBI ভাৰতীয় নাগৰিকৰ বাবে অভিযোগ সমাধান প্ৰক্ৰিয়া সৰল কৰে।',
      'whatwedo.desc': 'RBI ভাৰতীয় নাগৰিকৰ বাবে অভিযোগ সমাধান প্ৰক্ৰিয়া সৰল আৰু দ্ৰুত কৰে।',
      'whatwedo.howToFile': 'অভিযোগ কেনেকৈ দাখিল কৰিব',
      'whatwedo.whatWeCanHelp': 'আমি কি সহায় কৰিব পাৰো',
      'stats.tag': 'পৰিসংখ্যা',
      'stats.received': 'অভিযোগ প্ৰাপ্ত',
      'stats.handled': 'অভিযোগ পৰিচালিত',
      'stats.resolved': 'অভিযোগ সমাধান',
      'stats.receivedValue': '৯,৫০,০০০',
      'stats.handledValue': '৮,৭৫,০০০',
      'stats.resolvedValue': '৯৬%',
      'press.title': 'সংবাদ বিজ্ঞপ্তি',
      'press.viewAll': 'সকলো চাওক',
      'press.readMore': 'আৰু পঢ়ক',
      'press.month1': 'মাৰ্চ ২২',
      'press.title1': 'BE(A)WARE – বিত্তীয় প্ৰতাৰণাৰ কাৰ্যপদ্ধতি সম্পৰ্কীয় পুস্তিকা',
      'press.desc1': 'ৰিজাৰ্ভ বেংকে আজি "BE(A)WARE" পুস্তিকা প্ৰকাশ কৰিছে যিটো প্ৰতাৰকসকলৰ সাধাৰণ কাৰ্যপদ্ধতি আৰু বিত্তীয় লেনদেনৰ সময়ত ল\'ব লগা সাৱধানতা সম্পৰ্কে।',
      'press.month2': 'ফেব্ৰু ২২',
      'press.title2': 'RBI য়ে নিজৰ নামত নকলি ৱেবছাইট সম্পৰ্কে সতৰ্কবাণী দিছে',
      'press.desc2': 'ৰিজাৰ্ভ বেংকে জনসাধাৰণক নিজৰ নামত নকলি ৱেবছাইট সম্পৰ্কে সতৰ্ক কৰিছে।',
      'edu.tag': 'জন সচেতনতা',
      'edu.title': 'শিক্ষা আৰু সচেতনতা',
      'edu.watch': 'চাওক',
      'edu.read': 'পঢ়ক',
      'edu.card1Title': 'মৌলিক সঞ্চয় বেংক জমা একাউণ্ট (BSBDA)',
      'edu.card1Subtitle': 'মৌলিক সঞ্চয় বেংক জমা একাউণ্ট BSBDA',
      'edu.card2Title': 'অনধিকৃত ইলেক্ট্ৰনিক বেংকিং লেনদেনত গ্ৰাহকৰ দায়িত্ব',
      'edu.card2Subtitle': 'অনধিকৃত ইলেক্ট্ৰনিক বেংকিং লেনদেনত গ্ৰাহকৰ দায়িত্ব',
      'edu.card3Title': 'BE(A)WARE',
      'edu.card3Subtitle': 'বিত্তীয় প্ৰতাৰকসকলৰ কাৰ্যপদ্ধতি সম্পৰ্কীয় পুস্তিকা',
      'edu.card4Title': 'অনধিকৃত ইলেক্ট্ৰনিক বেংকিং লেনদেনত গ্ৰাহকৰ দায়িত্ব',
      'edu.card4Subtitle': 'মৌলিক সঞ্চয় বেংক জমা একাউণ্ট BSBDA',
      'faq.tag': 'সঘনাই সোধা প্ৰশ্ন',
      'faq.title': 'সঘনাই সোধা প্ৰশ্ন',
      'faq.q1': 'এই ৱেবছাইটৰ জৰিয়তে মই কি ধৰণৰ অভিযোগ দাখিল কৰিব পাৰো?',
      'faq.a1': 'এই ৱেবছাইটে ভাৰতীয় ৰিজাৰ্ভ বেংকৰ দ্বাৰা নিয়ন্ত্ৰিত বাণিজ্যিক বেংক, নগৰ সমবায় বেংক, অ-বেংকিং বিত্তীয় সংস্থা আৰু পেমেণ্ট ছিষ্টেম অংশগ্ৰহণকাৰীৰ সেৱা অভাৱ সম্পৰ্কীয় অভিযোগ দাখিলত সহায় কৰে।',
      'faq.q2': 'মই মোৰ অভিযোগৰ স্থিতি কেনেকৈ ট্ৰেক কৰিম?',
      'faq.a2': '"অভিযোগ ট্ৰেক" ক্লিক কৰি আপোনাৰ অভিযোগ নম্বৰ দি স্থিতি জানিব পাৰিব।',
      'faq.q3': 'অভিযোগ সমাধানৰ সময়সীমা কিমান?',
      'faq.a3': 'নিয়ন্ত্ৰিত সংস্থাই অভিযোগ পোৱাৰ ৩০ দিনৰ ভিতৰত সমাধান কৰিব লাগিব। সন্তুষ্ট নহ\'লে এই পৰ্টেলত অভিযোগ কৰিব পাৰে।',
      'dashboard.home': 'হোম',
      'dashboard.fileNew': 'নতুন অভিযোগ দাখিল',
      'dashboard.history': 'অভিযোগ ইতিহাস',
      'dashboard.id': 'আইডি',
      'dashboard.against': 'কাৰ বিৰুদ্ধে',
      'dashboard.date': 'অভিযোগ তাৰিখ',
      'dashboard.status': 'স্থিতি',
      'dashboard.comments': 'মন্তব্য',
      'dashboard.action': 'পদক্ষেপ',
      'dashboard.withdraw': 'প্ৰত্যাহাৰ',
      'dashboard.appeal': 'আপীল',
      'dashboard.act': 'পদক্ষেপ',
      'file.title': 'অভিযোগ দাখিল কৰক',
      'file.next': 'পৰৱৰ্তী',
      'file.previous': 'পূৰ্বৱৰ্তী',
      'file.submit': 'দাখিল কৰক',
      'track.title': 'আপোনাৰ অভিযোগ ট্ৰেক কৰক',
      'track.placeholder': 'অভিযোগ নম্বৰ লিখক',
      'track.search': 'বিচাৰক',
      'common.search': 'বিচাৰক',
      'common.cancel': 'বাতিল',
      'common.close': 'বন্ধ',
      'common.loading': 'ল\'ড হৈ আছে...',
    },
  };

  setLanguage(lang: Language): void {
    this.currentLang.set(lang);
    localStorage.setItem('cms_language', lang);
    document.documentElement.lang = lang;
  }

  t(key: string): string {
    const lang = this.currentLang();
    return this.translations[lang]?.[key]
      || this.translations['en']?.[key]
      || key;
  }

  private loadSavedLanguage(): Language {
    const saved = localStorage.getItem('cms_language');
    if (saved && this.isValidLanguage(saved)) return saved as Language;
    return 'en';
  }

  private isValidLanguage(lang: string): boolean {
    return ['en', 'hi', 'ta', 'te', 'bn', 'mr', 'gu', 'kn', 'ml', 'pa', 'or', 'as'].includes(lang);
  }
}
